/* eslint-disable */
/** AUTO-GENERATED by scripts/freeze-demo-ad-creatives.ts — do not edit by hand. */

import type { DemoCreativeTest } from "@/lib/demo/dashboard-demo-data";
import type { TimelineAd } from "@/components/competitor/tests-timeline/timeline-types";

export type FrozenScrapedAd = {
  id: string;
  platform: string;
  format: string;
  ad_text: string;
  ai_extracted_angle: string | null;
  first_seen_at: string;
  last_seen_at: string;
  is_active: boolean;
  frozen_creative_url: string;
};

export const FROZEN_ADS_SOURCE_SLUG = "adidas.com";
export const FROZEN_ADS_BRAND_NAME = "Adidas";

export const FROZEN_AD_BY_ID: Record<string, FrozenScrapedAd> = {
  "722a2218-8662-443f-8d27-18995208ea0c": {
    "id": "722a2218-8662-443f-8d27-18995208ea0c",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "identity · Hook: adidas International B.V. · Body: Brand awareness display",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/722a2218-8662-443f-8d27-18995208ea0c.png"
  },
  "3f000293-b8de-4e88-831b-d9a8b8fd9499": {
    "id": "3f000293-b8de-4e88-831b-d9a8b8fd9499",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "brand retargeting · Hook: adidas International B.V. · Body: Repeated brand impression with date range",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/3f000293-b8de-4e88-831b-d9a8b8fd9499.png"
  },
  "bea8ebee-4e35-4427-9705-41f185c4ce77": {
    "id": "bea8ebee-4e35-4427-9705-41f185c4ce77",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "Brand display · Hook: adidas International · Body: Brand awareness with date range",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/bea8ebee-4e35-4427-9705-41f185c4ce77.png"
  },
  "8fc2818b-9416-4f8e-94a1-c6d93b3b2b5b": {
    "id": "8fc2818b-9416-4f8e-94a1-c6d93b3b2b5b",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "identity · Hook: adidas International B.V. · Body: Brand awareness display",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/8fc2818b-9416-4f8e-94a1-c6d93b3b2b5b.png"
  },
  "e1a57570-6cbd-4f6c-8ad1-061dc051b7bf": {
    "id": "e1a57570-6cbd-4f6c-8ad1-061dc051b7bf",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "brand awareness · Hook: adidas International B.V. · Body: Brand-only display ad",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/e1a57570-6cbd-4f6c-8ad1-061dc051b7bf.png"
  },
  "eed8280f-6999-419f-ad7a-75a8b7522105": {
    "id": "eed8280f-6999-419f-ad7a-75a8b7522105",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "identity · Hook: adidas International B.V. · Body: Brand awareness display",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/eed8280f-6999-419f-ad7a-75a8b7522105.png"
  },
  "657e3604-275b-4384-b187-9d943342f7fb": {
    "id": "657e3604-275b-4384-b187-9d943342f7fb",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "brand awareness · Hook: adidas International B.V. · Body: Repeated brand display ad",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/657e3604-275b-4384-b187-9d943342f7fb.png"
  },
  "21041028-07ed-4087-a71b-3b70cc94c402": {
    "id": "21041028-07ed-4087-a71b-3b70cc94c402",
    "platform": "meta",
    "format": "image",
    "ad_text": "adidas ürünlerini keşfet!\nAdidas Çocuk Gazelle Ayakkabı Lifestyle\nAdidas.com.tr’den Gazelle Ayakkabı - Siyah Satın Al! Gazelle Ayakkabı - Siyah Ürününün Adidas’ın Türkiye’deki Resmi Online Shop’unda Bulunan Tüm Stillerine Ve Renklerine Göz At.\nShop Now",
    "ai_extracted_angle": "quality · Hook: adidas ürünlerini keşfet! · Body: Explore official adidas shop",
    "first_seen_at": "2026-06-01T07:00:00+00:00",
    "last_seen_at": "2026-07-03T15:11:16.939+00:00",
    "is_active": false,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/21041028-07ed-4087-a71b-3b70cc94c402.jpg"
  },
  "a1f8a56d-2085-4d04-929c-46f4388e3b3a": {
    "id": "a1f8a56d-2085-4d04-929c-46f4388e3b3a",
    "platform": "meta",
    "format": "image",
    "ad_text": "Refresh your wardrobe with adidas icons.\nadilette Slides\nShop Now",
    "ai_extracted_angle": "identity · Hook: Refresh your wardrobe with adidas icons · Body: Brand awareness for adidas slides",
    "first_seen_at": "2026-06-01T07:00:00+00:00",
    "last_seen_at": "2026-07-03T15:11:16.939+00:00",
    "is_active": false,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/a1f8a56d-2085-4d04-929c-46f4388e3b3a.jpg"
  },
  "85928b31-ebe1-4554-9a7d-32d65c2e88de": {
    "id": "85928b31-ebe1-4554-9a7d-32d65c2e88de",
    "platform": "meta",
    "format": "image",
    "ad_text": "Refresh your wardrobe with adidas icons.\nMundial Goal Shoes\nShop Now",
    "ai_extracted_angle": "identity · Hook: Refresh your wardrobe with adidas icons · Body: Brand-led product push",
    "first_seen_at": "2026-06-01T07:00:00+00:00",
    "last_seen_at": "2026-07-03T15:11:16.939+00:00",
    "is_active": false,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/85928b31-ebe1-4554-9a7d-32d65c2e88de.jpg"
  },
  "ccdeb672-c043-43ce-8a8c-c65c520a6f3c": {
    "id": "ccdeb672-c043-43ce-8a8c-c65c520a6f3c",
    "platform": "meta",
    "format": "image",
    "ad_text": "Refresh your wardrobe with adidas icons.\nadilette Slides\nShop Now",
    "ai_extracted_angle": "identity · Hook: Refresh your wardrobe with adidas icons · Body: Brand-led product push",
    "first_seen_at": "2026-06-01T07:00:00+00:00",
    "last_seen_at": "2026-07-03T17:14:07.7+00:00",
    "is_active": false,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/ccdeb672-c043-43ce-8a8c-c65c520a6f3c.jpg"
  },
  "3eb15684-aa0c-4141-949e-d047241f432b": {
    "id": "3eb15684-aa0c-4141-949e-d047241f432b",
    "platform": "meta",
    "format": "video",
    "ad_text": "Saha varsa, efsane de vardır #YouGotThis\n#YouGotThis\nLearn More",
    "ai_extracted_angle": "identity · Hook: Saha varsa, efsane de vardır #YouGotThis · Body: Brand awareness with soccer motivation",
    "first_seen_at": "2026-06-22T07:00:00+00:00",
    "last_seen_at": "2026-07-03T17:14:07.7+00:00",
    "is_active": false,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/3eb15684-aa0c-4141-949e-d047241f432b.jpg"
  },
  "15b383cd-693e-40ba-8c4b-791490003dd0": {
    "id": "15b383cd-693e-40ba-8c4b-791490003dd0",
    "platform": "meta",
    "format": "video",
    "ad_text": "Saha varsa, efsane de vardır #YouGotThis\n#YouGotThis\nLearn More",
    "ai_extracted_angle": "identity · Hook: Saha varsa, efsane de vardır #YouGotThis · Body: Brand inspiration video",
    "first_seen_at": "2026-06-22T07:00:00+00:00",
    "last_seen_at": "2026-07-03T15:11:16.939+00:00",
    "is_active": false,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/15b383cd-693e-40ba-8c4b-791490003dd0.jpg"
  },
  "23a038b8-e7f2-4d5b-8043-94f1ce066f89": {
    "id": "23a038b8-e7f2-4d5b-8043-94f1ce066f89",
    "platform": "meta",
    "format": "video",
    "ad_text": "Saha varsa, efsane de vardır #YouGotThis\n#YouGotThis\nLearn More",
    "ai_extracted_angle": "identity · Hook: Saha varsa, efsane de vardır #YouGotThis · Body: Brand awareness with soccer motivation",
    "first_seen_at": "2026-06-22T07:00:00+00:00",
    "last_seen_at": "2026-07-03T15:11:16.939+00:00",
    "is_active": false,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/23a038b8-e7f2-4d5b-8043-94f1ce066f89.jpg"
  },
  "030395e4-882e-4aeb-a533-0add5a9a6716": {
    "id": "030395e4-882e-4aeb-a533-0add5a9a6716",
    "platform": "meta",
    "format": "image",
    "ad_text": "Refresh your wardrobe with adidas icons.\nMundial Team Boots\nShop Now",
    "ai_extracted_angle": "identity · Hook: Refresh your wardrobe with adidas icons · Body: Brand awareness for adidas slides",
    "first_seen_at": "2026-06-12T07:00:00+00:00",
    "last_seen_at": "2026-07-06T16:20:38.702+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/030395e4-882e-4aeb-a533-0add5a9a6716.jpg"
  },
  "6cf3d059-d0b1-490d-ad01-c80a42e7655f": {
    "id": "6cf3d059-d0b1-490d-ad01-c80a42e7655f",
    "platform": "meta",
    "format": "image",
    "ad_text": "Take it up a notch in unmistakable adidas style\nadilette Slides\nShop Now",
    "ai_extracted_angle": "quality · Hook: Take it up a notch in unmistakable adidas style · Body: Style upgrade with product",
    "first_seen_at": "2026-05-21T07:00:00+00:00",
    "last_seen_at": "2026-07-06T16:20:38.702+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/6cf3d059-d0b1-490d-ad01-c80a42e7655f.jpg"
  },
  "97a65ab6-1e40-49bc-b700-d795909fe114": {
    "id": "97a65ab6-1e40-49bc-b700-d795909fe114",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-06-01 → 2026-07-14\n2026-06-01 – 2026-07-14",
    "ai_extracted_angle": "identity · Hook: adidas International B.V. · Body: Brand logo display on Google image ad",
    "first_seen_at": "2026-06-01T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/97a65ab6-1e40-49bc-b700-d795909fe114.png"
  },
  "785fd861-4989-4ef2-b57c-ef403c80be96": {
    "id": "785fd861-4989-4ef2-b57c-ef403c80be96",
    "platform": "google",
    "format": "image",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-04-01 → 2026-07-14\n2026-04-01 – 2026-07-14",
    "ai_extracted_angle": "brand awareness · Hook: adidas International B.V. · Body: Brand name and dates only",
    "first_seen_at": "2026-04-01T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/785fd861-4989-4ef2-b57c-ef403c80be96.png"
  },
  "6a575a45-3fc8-4433-a362-308386baf3f1": {
    "id": "6a575a45-3fc8-4433-a362-308386baf3f1",
    "platform": "linkedin",
    "format": "image",
    "ad_text": "Showing up in AI search isn’t enough. What AI says about your brand shapes buying decisions. Track your mentions, sentiment, & accuracy. Book a demo.%FIRSTNAME%",
    "ai_extracted_angle": "fear · Hook: Control what AI says about your brand · Body: AI brand monitoring & sentiment tracking tool",
    "first_seen_at": "2026-05-13T00:00:00+00:00",
    "last_seen_at": "2026-05-19T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/6a575a45-3fc8-4433-a362-308386baf3f1.jpg"
  },
  "c07715e5-aa6d-4fdc-b32e-cd6498492848": {
    "id": "c07715e5-aa6d-4fdc-b32e-cd6498492848",
    "platform": "linkedin",
    "format": "image",
    "ad_text": "Showing up in AI search isn’t enough. What AI says about your brand shapes buying decisions. Track your mentions, sentiment, & accuracy. Book a demo.%FIRSTNAME%",
    "ai_extracted_angle": "fear · Hook: Control what AI says about your brand · Body: AI brand monitoring & sentiment tracking tool",
    "first_seen_at": "2026-05-13T00:00:00+00:00",
    "last_seen_at": "2026-05-19T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/c07715e5-aa6d-4fdc-b32e-cd6498492848.jpg"
  },
  "5cd5a4ec-d624-4e6e-b0eb-9125ae40816b": {
    "id": "5cd5a4ec-d624-4e6e-b0eb-9125ae40816b",
    "platform": "pinterest",
    "format": "image",
    "ad_text": "UEFA CHAMPIONS LEAGUE FINAL LEAGUE BOX Fußball\nDer UEFA Champions League Final League Box Fußball wurde für alle entwickelt, die für das Spiel leben. Er bietet eine nahtlose Mischung aus dauerhafter Haltbarkeit und Performance.  Seine TPU-laminierte Oberfläche ist besonders lang…",
    "ai_extracted_angle": "quality · Hook: UEFA Champions League Final League Box Fußball · Body: Product quality and certification focus",
    "first_seen_at": "2026-05-02T22:00:00+00:00",
    "last_seen_at": "2026-06-27T22:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/5cd5a4ec-d624-4e6e-b0eb-9125ae40816b.jpg"
  },
  "ae489d43-7d3d-4b5b-a22c-c3db3dc0f329": {
    "id": "ae489d43-7d3d-4b5b-a22c-c3db3dc0f329",
    "platform": "pinterest",
    "format": "image",
    "ad_text": "Tiro 26 Competition Trainingsoberteil\nDas Tiro 26 Competition Trainingsoberteil wurde für alle entwickelt, die auf dem Spielfeld Höchstleistungen erbringen wollen. Mit seinem schlanken Design und den leistungsstarken Funktionen ist dieses Oberteil sowohl stylish als auch funktio…",
    "ai_extracted_angle": "quality · Hook: Tiro 26 Competition Trainingsoberteil · Body: Performance and style for training",
    "first_seen_at": "2026-04-08T22:00:00+00:00",
    "last_seen_at": "2026-06-27T22:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/ae489d43-7d3d-4b5b-a22c-c3db3dc0f329.jpg"
  },
  "43ea76a7-9142-440d-955d-92ea45a32df5": {
    "id": "43ea76a7-9142-440d-955d-92ea45a32df5",
    "platform": "snapchat",
    "format": "image",
    "ad_text": "Black Friday: bis zu 50 % Rabatt\nACTIVE · Review: APPROVED",
    "ai_extracted_angle": "discount · Hook: Black Friday: bis zu 50 % Rabatt · Body: Discount offer with approval badge",
    "first_seen_at": "2026-05-24T16:35:58.939+00:00",
    "last_seen_at": "2026-07-04T10:17:39.765+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/43ea76a7-9142-440d-955d-92ea45a32df5.jpg"
  },
  "684df3bf-b1fa-4e79-ae73-86313303d5f8": {
    "id": "684df3bf-b1fa-4e79-ae73-86313303d5f8",
    "platform": "snapchat",
    "format": "image",
    "ad_text": "YOU GOT THIS\nACTIVE · Review: APPROVED",
    "ai_extracted_angle": "identity · Hook: YOU GOT THIS · Body: Motivational brand awareness messaging",
    "first_seen_at": "2026-05-19T17:59:27.445+00:00",
    "last_seen_at": "2026-07-04T10:17:39.765+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/adidas.com/ads/684df3bf-b1fa-4e79-ae73-86313303d5f8.jpg"
  }
} as Record<string, FrozenScrapedAd>;

export const FROZEN_LIBRARY_AD_IDS: string[] = [
  "030395e4-882e-4aeb-a533-0add5a9a6716",
  "6cf3d059-d0b1-490d-ad01-c80a42e7655f",
  "a1f8a56d-2085-4d04-929c-46f4388e3b3a",
  "97a65ab6-1e40-49bc-b700-d795909fe114",
  "785fd861-4989-4ef2-b57c-ef403c80be96",
  "722a2218-8662-443f-8d27-18995208ea0c",
  "5cd5a4ec-d624-4e6e-b0eb-9125ae40816b",
  "ae489d43-7d3d-4b5b-a22c-c3db3dc0f329",
  "43ea76a7-9142-440d-955d-92ea45a32df5",
  "684df3bf-b1fa-4e79-ae73-86313303d5f8"
];

export const FROZEN_TIMELINE_AD_IDS: string[] = [
  "722a2218-8662-443f-8d27-18995208ea0c",
  "3f000293-b8de-4e88-831b-d9a8b8fd9499",
  "bea8ebee-4e35-4427-9705-41f185c4ce77",
  "8fc2818b-9416-4f8e-94a1-c6d93b3b2b5b",
  "e1a57570-6cbd-4f6c-8ad1-061dc051b7bf",
  "eed8280f-6999-419f-ad7a-75a8b7522105",
  "657e3604-275b-4384-b187-9d943342f7fb"
];

export const FROZEN_TIMELINE_ADS: TimelineAd[] = [
  {
    "id": "722a2218-8662-443f-8d27-18995208ea0c",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/adidas.com/ads/722a2218-8662-443f-8d27-18995208ea0c.png",
    "archived_creative_url": "/demo/frozen/adidas.com/ads/722a2218-8662-443f-8d27-18995208ea0c.png",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "identity · Hook: adidas International B.V. · Body: Brand awareness display",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "3f000293-b8de-4e88-831b-d9a8b8fd9499",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/adidas.com/ads/3f000293-b8de-4e88-831b-d9a8b8fd9499.png",
    "archived_creative_url": "/demo/frozen/adidas.com/ads/3f000293-b8de-4e88-831b-d9a8b8fd9499.png",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "brand retargeting · Hook: adidas International B.V. · Body: Repeated brand impression with date range",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "bea8ebee-4e35-4427-9705-41f185c4ce77",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/adidas.com/ads/bea8ebee-4e35-4427-9705-41f185c4ce77.png",
    "archived_creative_url": "/demo/frozen/adidas.com/ads/bea8ebee-4e35-4427-9705-41f185c4ce77.png",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "Brand display · Hook: adidas International · Body: Brand awareness with date range",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "8fc2818b-9416-4f8e-94a1-c6d93b3b2b5b",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/adidas.com/ads/8fc2818b-9416-4f8e-94a1-c6d93b3b2b5b.png",
    "archived_creative_url": "/demo/frozen/adidas.com/ads/8fc2818b-9416-4f8e-94a1-c6d93b3b2b5b.png",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "identity · Hook: adidas International B.V. · Body: Brand awareness display",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "e1a57570-6cbd-4f6c-8ad1-061dc051b7bf",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/adidas.com/ads/e1a57570-6cbd-4f6c-8ad1-061dc051b7bf.png",
    "archived_creative_url": "/demo/frozen/adidas.com/ads/e1a57570-6cbd-4f6c-8ad1-061dc051b7bf.png",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "brand awareness · Hook: adidas International B.V. · Body: Brand-only display ad",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "eed8280f-6999-419f-ad7a-75a8b7522105",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/adidas.com/ads/eed8280f-6999-419f-ad7a-75a8b7522105.png",
    "archived_creative_url": "/demo/frozen/adidas.com/ads/eed8280f-6999-419f-ad7a-75a8b7522105.png",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "identity · Hook: adidas International B.V. · Body: Brand awareness display",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "657e3604-275b-4384-b187-9d943342f7fb",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/adidas.com/ads/657e3604-275b-4384-b187-9d943342f7fb.png",
    "archived_creative_url": "/demo/frozen/adidas.com/ads/657e3604-275b-4384-b187-9d943342f7fb.png",
    "ad_text": "adidas International B.V. — adidas.com\nImage · Shown 2026-07-08 → 2026-07-14\n2026-07-08 – 2026-07-14",
    "ai_extracted_angle": "brand awareness · Hook: adidas International B.V. · Body: Repeated brand display ad",
    "first_seen_at": "2026-07-08T00:00:00+00:00",
    "last_seen_at": "2026-07-14T00:00:00+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  }
] as TimelineAd[];

export const FROZEN_CREATIVE_TESTS: DemoCreativeTest[] = [
  {
    "id": "364dbec8-7e71-4b35-8152-ddf942db6988",
    "launch_date": "2026-06-01",
    "platform": "meta",
    "ad_ids": [
      "21041028-07ed-4087-a71b-3b70cc94c402",
      "a1f8a56d-2085-4d04-929c-46f4388e3b3a",
      "85928b31-ebe1-4554-9a7d-32d65c2e88de",
      "ccdeb672-c043-43ce-8a8c-c65c520a6f3c"
    ],
    "winner_ad_id": null,
    "test_status": "no_clear_winner",
    "median_lifespan_days": 12,
    "max_lifespan_days": 32,
    "winner_lifespan_days": null,
    "ad_count": 4,
    "ads": [
      {
        "id": "21041028-07ed-4087-a71b-3b70cc94c402",
        "platform": "meta",
        "format": "image",
        "ad_text": "adidas ürünlerini keşfet!\nAdidas Çocuk Gazelle Ayakkabı Lifestyle\nAdidas.com.tr’den Gazelle Ayakkabı - Siyah Satın Al! Gazelle Ayakkabı - Siyah Ürününün Adidas’ın Türkiye’deki Resmi Online Shop’unda Bulunan Tüm Stillerine Ve Renklerine Göz At.\nShop Now",
        "ai_extracted_angle": "quality · Hook: adidas ürünlerini keşfet! · Body: Explore official adidas shop",
        "first_seen_at": "2026-06-01T07:00:00+00:00",
        "last_seen_at": "2026-07-03T15:11:16.939+00:00",
        "ad_creative_url": "/demo/frozen/adidas.com/ads/21041028-07ed-4087-a71b-3b70cc94c402.jpg",
        "archived_creative_url": "/demo/frozen/adidas.com/ads/21041028-07ed-4087-a71b-3b70cc94c402.jpg"
      },
      {
        "id": "a1f8a56d-2085-4d04-929c-46f4388e3b3a",
        "platform": "meta",
        "format": "image",
        "ad_text": "Refresh your wardrobe with adidas icons.\nadilette Slides\nShop Now",
        "ai_extracted_angle": "identity · Hook: Refresh your wardrobe with adidas icons · Body: Brand awareness for adidas slides",
        "first_seen_at": "2026-06-01T07:00:00+00:00",
        "last_seen_at": "2026-07-03T15:11:16.939+00:00",
        "ad_creative_url": "/demo/frozen/adidas.com/ads/a1f8a56d-2085-4d04-929c-46f4388e3b3a.jpg",
        "archived_creative_url": "/demo/frozen/adidas.com/ads/a1f8a56d-2085-4d04-929c-46f4388e3b3a.jpg"
      },
      {
        "id": "85928b31-ebe1-4554-9a7d-32d65c2e88de",
        "platform": "meta",
        "format": "image",
        "ad_text": "Refresh your wardrobe with adidas icons.\nMundial Goal Shoes\nShop Now",
        "ai_extracted_angle": "identity · Hook: Refresh your wardrobe with adidas icons · Body: Brand-led product push",
        "first_seen_at": "2026-06-01T07:00:00+00:00",
        "last_seen_at": "2026-07-03T15:11:16.939+00:00",
        "ad_creative_url": "/demo/frozen/adidas.com/ads/85928b31-ebe1-4554-9a7d-32d65c2e88de.jpg",
        "archived_creative_url": "/demo/frozen/adidas.com/ads/85928b31-ebe1-4554-9a7d-32d65c2e88de.jpg"
      },
      {
        "id": "ccdeb672-c043-43ce-8a8c-c65c520a6f3c",
        "platform": "meta",
        "format": "image",
        "ad_text": "Refresh your wardrobe with adidas icons.\nadilette Slides\nShop Now",
        "ai_extracted_angle": "identity · Hook: Refresh your wardrobe with adidas icons · Body: Brand-led product push",
        "first_seen_at": "2026-06-01T07:00:00+00:00",
        "last_seen_at": "2026-07-03T17:14:07.7+00:00",
        "ad_creative_url": "/demo/frozen/adidas.com/ads/ccdeb672-c043-43ce-8a8c-c65c520a6f3c.jpg",
        "archived_creative_url": "/demo/frozen/adidas.com/ads/ccdeb672-c043-43ce-8a8c-c65c520a6f3c.jpg"
      }
    ]
  },
  {
    "id": "5b9d6f5a-0d2e-451c-8f10-f85bb3b081b0",
    "launch_date": "2026-06-22",
    "platform": "meta",
    "ad_ids": [
      "3eb15684-aa0c-4141-949e-d047241f432b",
      "15b383cd-693e-40ba-8c4b-791490003dd0",
      "23a038b8-e7f2-4d5b-8043-94f1ce066f89"
    ],
    "winner_ad_id": null,
    "test_status": "no_clear_winner",
    "median_lifespan_days": 11,
    "max_lifespan_days": 11,
    "winner_lifespan_days": null,
    "ad_count": 3,
    "ads": [
      {
        "id": "3eb15684-aa0c-4141-949e-d047241f432b",
        "platform": "meta",
        "format": "video",
        "ad_text": "Saha varsa, efsane de vardır #YouGotThis\n#YouGotThis\nLearn More",
        "ai_extracted_angle": "identity · Hook: Saha varsa, efsane de vardır #YouGotThis · Body: Brand awareness with soccer motivation",
        "first_seen_at": "2026-06-22T07:00:00+00:00",
        "last_seen_at": "2026-07-03T17:14:07.7+00:00",
        "ad_creative_url": "/demo/frozen/adidas.com/ads/3eb15684-aa0c-4141-949e-d047241f432b.jpg",
        "archived_creative_url": "/demo/frozen/adidas.com/ads/3eb15684-aa0c-4141-949e-d047241f432b.jpg"
      },
      {
        "id": "15b383cd-693e-40ba-8c4b-791490003dd0",
        "platform": "meta",
        "format": "video",
        "ad_text": "Saha varsa, efsane de vardır #YouGotThis\n#YouGotThis\nLearn More",
        "ai_extracted_angle": "identity · Hook: Saha varsa, efsane de vardır #YouGotThis · Body: Brand inspiration video",
        "first_seen_at": "2026-06-22T07:00:00+00:00",
        "last_seen_at": "2026-07-03T15:11:16.939+00:00",
        "ad_creative_url": "/demo/frozen/adidas.com/ads/15b383cd-693e-40ba-8c4b-791490003dd0.jpg",
        "archived_creative_url": "/demo/frozen/adidas.com/ads/15b383cd-693e-40ba-8c4b-791490003dd0.jpg"
      },
      {
        "id": "23a038b8-e7f2-4d5b-8043-94f1ce066f89",
        "platform": "meta",
        "format": "video",
        "ad_text": "Saha varsa, efsane de vardır #YouGotThis\n#YouGotThis\nLearn More",
        "ai_extracted_angle": "identity · Hook: Saha varsa, efsane de vardır #YouGotThis · Body: Brand awareness with soccer motivation",
        "first_seen_at": "2026-06-22T07:00:00+00:00",
        "last_seen_at": "2026-07-03T15:11:16.939+00:00",
        "ad_creative_url": "/demo/frozen/adidas.com/ads/23a038b8-e7f2-4d5b-8043-94f1ce066f89.jpg",
        "archived_creative_url": "/demo/frozen/adidas.com/ads/23a038b8-e7f2-4d5b-8043-94f1ce066f89.jpg"
      }
    ]
  }
] as DemoCreativeTest[];

export function getFrozenCreativeUrl(adId: string): string | null {
  return FROZEN_AD_BY_ID[adId]?.frozen_creative_url ?? null;
}
