/* eslint-disable */
/** AUTO-GENERATED by scripts/freeze-demo-organic.ts — do not edit by hand. */

export type FrozenOrganicPost = {
  id: string;
  platform: string;
  content: string;
  likes: number;
  comments: number;
  views?: number;
  postedAt: string;
  previewUrl: string | null;
  gradient: string;
  isVideo?: boolean;
};

export const FROZEN_ORGANIC_SOURCE_SLUG = "adidas.com";
export const FROZEN_ORGANIC_BRAND_NAME = "Adidas";

export const FROZEN_ORGANIC_POSTS: FrozenOrganicPost[] = [
  {
    "id": "19e86076-3c6d-41b8-b731-d31b253c804a",
    "platform": "facebook",
    "content": "A shared moment on football’s biggest stage. Delivering the Trionda match ball for today’s FIFA World Cup Quarter Final in Miami.",
    "likes": 16737,
    "comments": 38,
    "postedAt": "3d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/19e86076-3c6d-41b8-b731-d31b253c804a.jpg",
    "gradient": "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)",
    "isVideo": false
  },
  {
    "id": "5032c3e0-618c-4872-88f2-dd6dab813214",
    "platform": "facebook",
    "content": "Just keep watching Tate McRae delivers the Trionda match ball for Spain vs Belgium FIFA World Cup Quarter Final",
    "likes": 7708,
    "comments": 90,
    "postedAt": "4d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/5032c3e0-618c-4872-88f2-dd6dab813214.jpg",
    "gradient": "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)",
    "isVideo": false
  },
  {
    "id": "ad4c80ed-dbbc-4a7d-a0a4-b328061bd235",
    "platform": "linkedin",
    "content": "Home of Soccer in NYC brought football from the pitch to the skyline and beyond ⚽✨ Thousands of fans gathered last week at Brooklyn Bridge…",
    "likes": 60,
    "comments": 1,
    "postedAt": "13d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/ad4c80ed-dbbc-4a7d-a0a4-b328061bd235.jpg",
    "gradient": "linear-gradient(135deg, #0a2540 0%, #0a66c2 55%, #70b5f9 100%)",
    "isVideo": false
  },
  {
    "id": "334b5f98-f555-4793-8ee8-d5a705829735",
    "platform": "facebook",
    "content": "Straight from The Sheriff’s mouth @vol_sports Welcome to the \\\\\\ family.",
    "likes": 409,
    "comments": 30,
    "postedAt": "13d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/334b5f98-f555-4793-8ee8-d5a705829735.jpg",
    "gradient": "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)",
    "isVideo": false
  },
  {
    "id": "a1bdb6cf-a913-4765-82be-b1239af60b54",
    "platform": "youtube",
    "content": "Even I need some ME time sometimes 🤓 #fifaworldcup #adidas #pedri #cubarsi",
    "likes": 246,
    "comments": 10,
    "views": 2522,
    "postedAt": "13d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/a1bdb6cf-a913-4765-82be-b1239af60b54.jpg",
    "gradient": "linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #f87171 100%)",
    "isVideo": false
  },
  {
    "id": "b1d9466c-965b-45ae-8445-f2be00d82ace",
    "platform": "youtube",
    "content": "Just a few legends putting their skills to the test ⚽#adidas #pogba #kaka #marcelo #fifaworldcup2026",
    "likes": 288,
    "comments": 5,
    "views": 3162,
    "postedAt": "13d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/b1d9466c-965b-45ae-8445-f2be00d82ace.jpg",
    "gradient": "linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #f87171 100%)",
    "isVideo": false
  },
  {
    "id": "10292624-444f-4b2f-a8b6-b50f631ca7e9",
    "platform": "linkedin",
    "content": "Movement, momentum, and meaningful connections at Sports Day in Korea 🏃‍➡️🫶 This summer, our much-anticipated Sports Day returned, bringi…",
    "likes": 217,
    "comments": 4,
    "postedAt": "13d ago",
    "previewUrl": null,
    "gradient": "linear-gradient(135deg, #0a2540 0%, #0a66c2 55%, #70b5f9 100%)",
    "isVideo": false
  },
  {
    "id": "281cd2ee-c2cc-464c-a152-a3331156c476",
    "platform": "linkedin",
    "content": "📍 Bangkok’s most exciting place to be in the heart of Song Wat ✨ We didn't set out to open just another store in Bangkok. The ambition was…",
    "likes": 218,
    "comments": 7,
    "postedAt": "13d ago",
    "previewUrl": null,
    "gradient": "linear-gradient(135deg, #0a2540 0%, #0a66c2 55%, #70b5f9 100%)",
    "isVideo": false
  },
  {
    "id": "6bbbc77a-901a-4813-bbd9-e7e91d621467",
    "platform": "youtube",
    "content": "Dream Team ⚡❤️#adidasfamily #football",
    "likes": 1002,
    "comments": 14,
    "views": 13478,
    "postedAt": "14d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/6bbbc77a-901a-4813-bbd9-e7e91d621467.jpg",
    "gradient": "linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #f87171 100%)",
    "isVideo": false
  },
  {
    "id": "8279b2e6-fb14-4b37-ad51-0fe343bf5ad0",
    "platform": "linkedin",
    "content": "What does confidence mean for one of the biggest names in Rugby?🏉🏟️ This week, we welcomed Ellie Kildunne, English rugby player and adida…",
    "likes": 381,
    "comments": 9,
    "postedAt": "14d ago",
    "previewUrl": "/demo/frozen/adidas.com/organic/8279b2e6-fb14-4b37-ad51-0fe343bf5ad0.jpg",
    "gradient": "linear-gradient(135deg, #0a2540 0%, #0a66c2 55%, #70b5f9 100%)",
    "isVideo": false
  }
];

export const FROZEN_ORGANIC_HANDLES = {
  "instagram": "adidas",
  "tiktok": "adidas",
  "youtube": "https://www.youtube.com/@adidas",
  "linkedin": "https://www.linkedin.com/company/adidas",
  "x": "@adidas",
  "facebook": "https://www.facebook.com/adidas"
};
