/* eslint-disable */
/** AUTO-GENERATED by scripts/freeze-demo-assets.ts — do not edit by hand. */

import type { PageDetailStaticPayload } from "@/components/website-tracker/PageDetailDrawer";
import type { DemoLandingPageChangeRow } from "@/lib/demo/demo-landing-page-changes-payload";

export type FrozenTrackedPageCard = {
  id: string;
  label: string;
  url: string;
  status: string;
  lastChecked: string;
  thumbnailUrl: string | null;
};

export const FROZEN_WEBSITE_SOURCE_SLUG = "neptunas.lt";
export const FROZEN_WEBSITE_COMPETITOR_NAME = "Neptunas";

export const FROZEN_TRACKED_PAGES: FrozenTrackedPageCard[] = [
  {
    "id": "fp-fc4725ebd37e",
    "label": "Homepage",
    "url": "neptunas.lt",
    "status": "No change",
    "lastChecked": "1d ago",
    "thumbnailUrl": "/demo/frozen/neptunas.lt/pages/fp-fc4725ebd37e/3ab61ee8-31ec-4446-acee-51cc893dcb86-hero.png"
  },
  {
    "id": "fp-cbeaf8bff094",
    "label": "Rival",
    "url": "spyrival.com",
    "status": "Changed",
    "lastChecked": "13h ago",
    "thumbnailUrl": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc-hero.png"
  },
  {
    "id": "fp-de715913057d",
    "label": "Neptunas 2026",
    "url": "coca-cola.com/lt/lt/offerings/neptunas-2026?af_xp=qr&af_sub1=LT&source_caller=ui&id=1777886137525&pid=QR_code&action=win_category&shortlink=9u7ueaj8&af_adset=META+Paid&deep_link_value=https%3A%2F%2Fstories.onelink.me%2FWz78%2F9u7ueaj8&af_channel=META&c=EU2698CMO153&utm_segment=1PD-0042-023-001-171-1&utm_source_platform=Facebook&utm_marketing_tactic=CLICKS",
    "status": "No change",
    "lastChecked": "8d ago",
    "thumbnailUrl": "/demo/frozen/neptunas.lt/pages/fp-de715913057d/f30f7139-ef61-4fbd-9bf1-62199e762f8f-hero.png"
  }
];

export const FROZEN_PAGE_DETAILS: Record<string, PageDetailStaticPayload> = {
  "fp-fc4725ebd37e": {
    "page": {
      "id": "fp-fc4725ebd37e",
      "url": "https://neptunas.lt/",
      "label": "Homepage",
      "page_type": "homepage",
      "is_active": true,
      "auto_detected_from": null,
      "last_screenshotted_at": "2026-07-14T02:03:14.794+00:00",
      "next_screenshot_at": "2026-07-17T02:03:14.794+00:00",
      "animation_calibration_status": "done",
      "animation_calibrated_at": "2026-07-14T02:04:15.085+00:00",
      "latestSnapshot": {
        "id": "3ab61ee8-31ec-4446-acee-51cc893dcb86",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-fc4725ebd37e/3ab61ee8-31ec-4446-acee-51cc893dcb86-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-fc4725ebd37e/3ab61ee8-31ec-4446-acee-51cc893dcb86-hero.png",
        "page_text": {
          "full_text": "[Skip to content](https://www.coca-cola.com/lt/lt/brands/neptunas#maincontent) [![Coca Cola Company Logo](https://www.coca-cola.com/content/dam/onexp/lt/lt/logo-color/lithuania-coca-cola-logo_black_600x96.png)](https://www.coca-cola.com/lt/lt) - [Mūsų prekių ženklai](https://www.coca-cola.com/lt/lt/brands) - [Sužinokite](https://www.coca-cola.com/lt/lt/brands/neptunas#) - [SPRITE SUMMER](https://www.coca-cola.com/lt/lt/offerings/sprite-summer) - [„Fuzetea – experience everyday“](https://www.coca-cola.com/lt/lt/offerings/made-of-fusion) - [Pasinaudok proga pasikeisti su „Neptūnu“](https://www.coca-cola.com/lt/lt/offerings/neptunas-2026) - [**Peržiūrėti viską**](https://www.coca-cola.com/lt/lt/offerings) - [Poveikis](https://www.coca-cola.com/lt/lt/brands/neptunas#) - [Tvarumas](https://www.coca-cola.com/lt/lt/sustainability) - [Socialinė veikla](https://www.coca-cola.com/lt/lt/social) - [Sveikata ir gerovė](https://www.coca-cola.com/lt/lt/sveikata-ir-gerove) - [Programėl"
        },
        "pixel_diff_pct": null,
        "has_meaningful_change": false,
        "change_analysis": {},
        "taken_at": "2026-07-14T02:03:14.605845+00:00",
        "status": "ok"
      }
    },
    "stats": {
      "totalSnapshots": 1,
      "changeCount": 0,
      "firstSnapshotAt": "2026-07-14T02:03:14.605845+00:00",
      "lastSnapshotAt": "2026-07-14T02:03:14.605845+00:00"
    },
    "snapshots": [
      {
        "id": "3ab61ee8-31ec-4446-acee-51cc893dcb86",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-fc4725ebd37e/3ab61ee8-31ec-4446-acee-51cc893dcb86-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-fc4725ebd37e/3ab61ee8-31ec-4446-acee-51cc893dcb86-hero.png",
        "page_text": {
          "full_text": "[Skip to content](https://www.coca-cola.com/lt/lt/brands/neptunas#maincontent) [![Coca Cola Company Logo](https://www.coca-cola.com/content/dam/onexp/lt/lt/logo-color/lithuania-coca-cola-logo_black_600x96.png)](https://www.coca-cola.com/lt/lt) - [Mūsų prekių ženklai](https://www.coca-cola.com/lt/lt/brands) - [Sužinokite](https://www.coca-cola.com/lt/lt/brands/neptunas#) - [SPRITE SUMMER](https://www.coca-cola.com/lt/lt/offerings/sprite-summer) - [„Fuzetea – experience everyday“](https://www.coca-cola.com/lt/lt/offerings/made-of-fusion) - [Pasinaudok proga pasikeisti su „Neptūnu“](https://www.coca-cola.com/lt/lt/offerings/neptunas-2026) - [**Peržiūrėti viską**](https://www.coca-cola.com/lt/lt/offerings) - [Poveikis](https://www.coca-cola.com/lt/lt/brands/neptunas#) - [Tvarumas](https://www.coca-cola.com/lt/lt/sustainability) - [Socialinė veikla](https://www.coca-cola.com/lt/lt/social) - [Sveikata ir gerovė](https://www.coca-cola.com/lt/lt/sveikata-ir-gerove) - [Programėl"
        },
        "pixel_diff_pct": null,
        "has_meaningful_change": false,
        "change_analysis": {},
        "taken_at": "2026-07-14T02:03:14.605845+00:00",
        "status": "ok"
      }
    ]
  },
  "fp-cbeaf8bff094": {
    "page": {
      "id": "fp-cbeaf8bff094",
      "url": "https://spy-rival.com/",
      "label": "Rival",
      "page_type": "custom",
      "is_active": true,
      "auto_detected_from": null,
      "last_screenshotted_at": "2026-07-15T02:05:35.653+00:00",
      "next_screenshot_at": "2026-07-18T02:05:35.653+00:00",
      "animation_calibration_status": "done",
      "animation_calibrated_at": "2026-07-15T02:05:27.752+00:00",
      "latestSnapshot": {
        "id": "aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc-hero.png",
        "page_text": {
          "cta_text": "Contact us",
          "headline": "Competitor spying on autopilot",
          "full_text": "Competitor spying on autopilot Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes. Contact us paid ads organic email connected into one dashboard",
          "subheadline": "Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform."
        },
        "pixel_diff_pct": 10.11,
        "has_meaningful_change": true,
        "change_analysis": {
          "urgency": "high",
          "what_to_do": "Run a test adding a 'Contact us' or 'Book a demo' secondary CTA alongside your existing 'TRY FOR FREE' button — Rival should capture enterprise-intent visitors without abandoning the self-serve funnel that Neptunas appears to be walking away from, creating an opportunity to win SMB and mid-market users that Neptunas is deprioritizing.",
          "threat_score": 7,
          "what_changed": "1. Hero CTA button changed from 'TRY FOR FREE' to 'Contact us' — both in the nav and the main hero button. 2. Hero background changed from a blue gradient to a light grey/white gradient. 3. The feature cards row below the hero (Paid ads, Organic, Email, Autopilot, MCP with checkmarks) was replaced with a new icon row showing individual platform logos grouped by category (paid ads: Meta, Google, TikTok, LinkedIn, Pinterest, Snapchat; organic: Instagram, TikTok, YouTube, LinkedIn, X; email: envelope icon) with a 'connected into one dashboard' label. 4. Headline capitalization changed from all-lowercase 'competitor spying on autopilot' to title-case 'Competitor spying on autopilot'. 5. At y=8800, the previous section showed a three-column pricing grid (Starter $40, Pro $60, Agency $100) with 'TRY FOR FREE' buttons. The new section at y=8800 shows an Enterprise plan with 'Custom pricing' and 'Volume-based · annual contracts available' — the self-serve pricing tiers are no longer visible at this scroll depth, replaced by an enterprise-focused card.",
          "visual_changes": [
            {
              "id": "region_1",
              "label": "Hero section",
              "section": "hero",
              "after_color": "#edf3f9",
              "before_color": "#e1e7ec",
              "color_changed": true,
              "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_1.png",
              "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_1.png"
            },
            {
              "id": "region_2",
              "label": "Pricing section",
              "section": "pricing",
              "after_color": "#9eb9c8",
              "before_color": "#a9c0ce",
              "color_changed": true,
              "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_2.png",
              "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_2.png"
            },
            {
              "id": "region_3",
              "label": "Hero section",
              "section": "hero",
              "after_color": "#e5e8ef",
              "before_color": "#b8cee0",
              "color_changed": true,
              "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_3.png",
              "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_3.png"
            }
          ],
          "mask_overlap_pct": 0,
          "sections_changed": [
            "hero",
            "pricing",
            "cta",
            "nav"
          ],
          "change_confidence": "confirmed",
          "ignored_animation": false,
          "strategic_interpretation": "This is a significant strategic pivot from a self-serve PLG (product-led growth) motion to an enterprise/sales-led motion. Removing 'TRY FOR FREE' and replacing it with 'Contact us' signals they are no longer acquiring users through a free trial funnel — they want inbound sales conversations instead. The pricing section shift toward Enterprise/Custom pricing reinforces this: they may have found that free trial users churned quickly or had low LTV, and are repositioning toward larger accounts (agencies, growth teams) that convert better through sales. The platform logo grid replaces the feature card checklist, likely to visually communicate breadth of coverage more quickly to enterprise buyers evaluating integrations. This could also mean they are testing whether a sales-qualified lead flow converts better than self-serve signups."
        },
        "taken_at": "2026-07-15T02:05:06.849035+00:00",
        "status": "ok"
      }
    },
    "stats": {
      "totalSnapshots": 5,
      "changeCount": 4,
      "firstSnapshotAt": "2026-07-06T00:09:02.559279+00:00",
      "lastSnapshotAt": "2026-07-15T02:05:06.849035+00:00"
    },
    "snapshots": [
      {
        "id": "aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc-hero.png",
        "page_text": {
          "cta_text": "Contact us",
          "headline": "Competitor spying on autopilot",
          "full_text": "Competitor spying on autopilot Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes. Contact us paid ads organic email connected into one dashboard",
          "subheadline": "Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform."
        },
        "pixel_diff_pct": 10.11,
        "has_meaningful_change": true,
        "change_analysis": {
          "urgency": "high",
          "what_to_do": "Run a test adding a 'Contact us' or 'Book a demo' secondary CTA alongside your existing 'TRY FOR FREE' button — Rival should capture enterprise-intent visitors without abandoning the self-serve funnel that Neptunas appears to be walking away from, creating an opportunity to win SMB and mid-market users that Neptunas is deprioritizing.",
          "threat_score": 7,
          "what_changed": "1. Hero CTA button changed from 'TRY FOR FREE' to 'Contact us' — both in the nav and the main hero button. 2. Hero background changed from a blue gradient to a light grey/white gradient. 3. The feature cards row below the hero (Paid ads, Organic, Email, Autopilot, MCP with checkmarks) was replaced with a new icon row showing individual platform logos grouped by category (paid ads: Meta, Google, TikTok, LinkedIn, Pinterest, Snapchat; organic: Instagram, TikTok, YouTube, LinkedIn, X; email: envelope icon) with a 'connected into one dashboard' label. 4. Headline capitalization changed from all-lowercase 'competitor spying on autopilot' to title-case 'Competitor spying on autopilot'. 5. At y=8800, the previous section showed a three-column pricing grid (Starter $40, Pro $60, Agency $100) with 'TRY FOR FREE' buttons. The new section at y=8800 shows an Enterprise plan with 'Custom pricing' and 'Volume-based · annual contracts available' — the self-serve pricing tiers are no longer visible at this scroll depth, replaced by an enterprise-focused card.",
          "visual_changes": [
            {
              "id": "region_1",
              "label": "Hero section",
              "section": "hero",
              "after_color": "#edf3f9",
              "before_color": "#e1e7ec",
              "color_changed": true,
              "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_1.png",
              "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_1.png"
            },
            {
              "id": "region_2",
              "label": "Pricing section",
              "section": "pricing",
              "after_color": "#9eb9c8",
              "before_color": "#a9c0ce",
              "color_changed": true,
              "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_2.png",
              "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_2.png"
            },
            {
              "id": "region_3",
              "label": "Hero section",
              "section": "hero",
              "after_color": "#e5e8ef",
              "before_color": "#b8cee0",
              "color_changed": true,
              "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_3.png",
              "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_3.png"
            }
          ],
          "mask_overlap_pct": 0,
          "sections_changed": [
            "hero",
            "pricing",
            "cta",
            "nav"
          ],
          "change_confidence": "confirmed",
          "ignored_animation": false,
          "strategic_interpretation": "This is a significant strategic pivot from a self-serve PLG (product-led growth) motion to an enterprise/sales-led motion. Removing 'TRY FOR FREE' and replacing it with 'Contact us' signals they are no longer acquiring users through a free trial funnel — they want inbound sales conversations instead. The pricing section shift toward Enterprise/Custom pricing reinforces this: they may have found that free trial users churned quickly or had low LTV, and are repositioning toward larger accounts (agencies, growth teams) that convert better through sales. The platform logo grid replaces the feature card checklist, likely to visually communicate breadth of coverage more quickly to enterprise buyers evaluating integrations. This could also mean they are testing whether a sales-qualified lead flow converts better than self-serve signups."
        },
        "taken_at": "2026-07-15T02:05:06.849035+00:00",
        "status": "ok"
      },
      {
        "id": "ef88aba3-8119-48b7-8a9c-eb4f7933c9ea",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/ef88aba3-8119-48b7-8a9c-eb4f7933c9ea-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/ef88aba3-8119-48b7-8a9c-eb4f7933c9ea-hero.png",
        "page_text": {
          "cta_text": "TRY FOR FREE",
          "headline": "competitor spying on autopilot",
          "full_text": "competitor spying on autopilot\n\nCompetitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes.\n\nTRY FOR FREE\n\n- Paid ads\n\n- Organic\n\n- Email\n\n- Autopilot\n\n- MCP",
          "subheadline": "Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.",
          "pricing_tiers": []
        },
        "pixel_diff_pct": 13.96,
        "has_meaningful_change": true,
        "change_analysis": {
          "urgency": "low",
          "what_to_do": "Audit your own social proof logo bar — if logos are small or hard to read at a glance, increase their size and spacing immediately. Rival is signaling this is a conversion lever worth testing.",
          "threat_score": 3,
          "what_changed": "The social proof logo bar at the bottom of the page was updated. In the previous version, logos were displayed at a smaller scale with tighter spacing and included brands like NIO GROUP, NOCCO, NA-KD, Santare, foodspring, manucurist, and DESENIO GROUP. In the new version, the same logos are displayed larger, with more generous spacing between them, and the carousel order/positioning has shifted — DESENIO GROUP and NA-KD are now more prominently centered and larger in the visible frame. The color of the 'on autopilot' headline text also appears to have shifted from a brighter blue to a darker navy/dark blue tone.",
          "sections_changed": [
            "hero",
            "social_proof"
          ],
          "change_confidence": "suspected_ab",
          "strategic_interpretation": "Two things are happening here. First, the logo bar redesign is a deliberate trust signal amplification — making logos bigger and more readable reduces visual noise and increases perceived credibility. They likely A/B tested this and found that larger, cleaner logo displays improve conversion by making brand recognition faster. Second, the headline color change from bright blue to dark navy suggests they may be testing contrast and readability, possibly responding to accessibility concerns or finding that the softer dark tone converts better against the light gradient background. Both changes point to a team that is actively optimizing above-the-fold trust and clarity rather than making structural changes."
        },
        "taken_at": "2026-07-07T08:15:20.049143+00:00",
        "status": "ok"
      },
      {
        "id": "ce175421-d6e1-42e6-a3ee-9722e06ef5b6",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/ce175421-d6e1-42e6-a3ee-9722e06ef5b6-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/ce175421-d6e1-42e6-a3ee-9722e06ef5b6-hero.png",
        "page_text": {
          "cta_text": "TRY FOR FREE",
          "headline": "competitor spying on autopilot",
          "full_text": "competitor spying on autopilot\n\nCompetitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes.\n\nTRY FOR FREE\n\n- Paid ads\n\n- Organic\n\n- Email\n\n- Autopilot\n\n- MCP",
          "subheadline": "Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes.",
          "pricing_tiers": []
        },
        "pixel_diff_pct": 26.74,
        "has_meaningful_change": true,
        "change_analysis": {
          "urgency": "high",
          "what_to_do": "Counter their 'autopilot' positioning by explicitly calling out your own automation and alerting features in your hero — if you have alerts, AI summaries, or scheduled reports, make those the headline benefit, not just the feature list. Don't let them own the 'set and forget' competitive intelligence narrative.",
          "threat_score": 8,
          "what_changed": "The hero headline changed from '#1 free adspy tool' to 'competitor spying on autopilot' — a significant reframe from feature/positioning claim to outcome/benefit language. The subheadline copy also changed from platform-listing copy ('tracking every competitor ad across Meta, Google, TikTok...') to capability-bundling copy ('Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes'). The hero UI mockup was replaced entirely: instead of showing the Ad Library dashboard with tabs and scraped creatives, they now show five feature category cards (Paid ads, Organic, Email, Autopilot, MCP) with platform icons and checkmarks. A social proof logo bar was added below the fold featuring brand logos including NA-KD, Nocco, foodspring, Manucurist Paris, and Desenio Group. The 'free' positioning was deprioritized — removed from the headline entirely.",
          "sections_changed": [
            "hero",
            "social_proof"
          ],
          "change_confidence": "confirmed",
          "strategic_interpretation": "They're moving away from competing on 'free' as a primary hook — likely because it attracts low-quality users or commoditizes their brand. The shift to 'autopilot' framing signals they're repositioning toward automation and passive intelligence rather than a DIY research tool. The new feature cards (especially 'Autopilot' and 'MCP') suggest they're launching or emphasizing AI-driven features and want those to anchor the value prop. Adding a logo bar with recognizable DTC/ecom brands (NA-KD, foodspring) is a deliberate trust signal targeting mid-market ecommerce teams. This looks like a conversion optimization test betting that outcome-driven copy + social proof outperforms the 'free tool' positioning they built the brand on."
        },
        "taken_at": "2026-07-06T12:16:11.460924+00:00",
        "status": "ok"
      },
      {
        "id": "f17a7f69-d445-4e0d-b615-dd4c7f8907ba",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/f17a7f69-d445-4e0d-b615-dd4c7f8907ba-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/f17a7f69-d445-4e0d-b615-dd4c7f8907ba-hero.png",
        "page_text": {
          "cta_text": "TRY FOR FREE",
          "headline": "#1 free adspy tool",
          "full_text": "Spy Rival is the best adspy tool for tracking every competitor ad across Meta, Google, TikTok, LinkedIn, Pinterest & Snapchat — all in one dashboard.",
          "subheadline": "Spy Rival is the best adspy tool for tracking every competitor ad across Meta, Google, TikTok, LinkedIn, Pinterest & Snapchat — all in one dashboard.",
          "pricing_tiers": []
        },
        "pixel_diff_pct": 3.92,
        "has_meaningful_change": true,
        "change_analysis": {
          "urgency": "low",
          "what_to_do": "No action required on this change specifically — monitor for follow-up changes to this page over the next 1-2 weeks as this minor tweak may precede a larger redesign or copy test.",
          "threat_score": 1,
          "what_changed": "The two versions appear visually identical based on the screenshot comparison. The 3.92% pixel difference is minimal and no text changes were detected in headline, CTA, or pricing. The change is likely a very subtle visual adjustment — possibly a minor spacing tweak, font rendering difference, or a small image/background gradient shift in the hero section that doesn't register as a meaningful content change.",
          "sections_changed": [
            "hero"
          ],
          "strategic_interpretation": "This looks like a micro-optimization or a technical fix rather than a strategic move. Could be A/B testing a subtle background gradient or shadow tweak in the hero to improve readability or visual polish. No signal of competitive urgency here — they're not changing messaging or offers, just potentially tidying up the UI."
        },
        "taken_at": "2026-07-06T00:12:05.767307+00:00",
        "status": "ok"
      },
      {
        "id": "55c25b33-d03c-416f-9849-fda41a8fb9cd",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/55c25b33-d03c-416f-9849-fda41a8fb9cd-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/55c25b33-d03c-416f-9849-fda41a8fb9cd-hero.png",
        "page_text": {
          "cta_text": "TRY FOR FREE",
          "headline": "#1 free adspy tool",
          "full_text": "AdSpy\n\nMeta AdSpy Google AdSpy TikTok AdSpy LinkedIn AdSpy Pinterest AdSpy Snapchat AdSpy\n\nFeatures\n\nMulti-platform Ad Library Strategy Map Three Moves Stealable Angles Copy Vault Timeline Activity Score Audience Inference Monday Digest Smart Platform Prioritization Email Marketing Intelligence\n\nPricing\n\nResources\n\nTutorials Blog Tools\n\nTRY FOR FREE\n\nTRY FOR FREE\n\n#1 free adspy tool\n\nSpy Rival is the best adspy tool for tracking every competitor ad across Meta, Google, TikTok, LinkedIn, Pinterest & Snapchat — all in one dashboard.\n\nTRY FOR FREE",
          "subheadline": "Spy Rival is the best adspy tool for tracking every competitor ad across Meta, Google, TikTok, LinkedIn, Pinterest & Snapchat — all in one dashboard.",
          "pricing_tiers": []
        },
        "pixel_diff_pct": null,
        "has_meaningful_change": false,
        "change_analysis": {},
        "taken_at": "2026-07-06T00:09:02.559279+00:00",
        "status": "ok"
      }
    ]
  },
  "fp-de715913057d": {
    "page": {
      "id": "fp-de715913057d",
      "url": "https://coca-cola.com/lt/lt/offerings/neptunas-2026?af_xp=qr&af_sub1=LT&source_caller=ui&id=1777886137525&pid=QR_code&action=win_category&shortlink=9u7ueaj8&af_adset=META+Paid&deep_link_value=https%3A%2F%2Fstories.onelink.me%2FWz78%2F9u7ueaj8&af_channel=META&c=EU2698CMO153&utm_segment=1PD-0042-023-001-171-1&utm_source_platform=Facebook&utm_marketing_tactic=CLICKS",
      "label": "Neptunas 2026",
      "page_type": "custom",
      "is_active": false,
      "auto_detected_from": "ads",
      "last_screenshotted_at": "2026-07-06T18:05:34.577+00:00",
      "next_screenshot_at": null,
      "animation_calibration_status": "pending",
      "animation_calibrated_at": null,
      "latestSnapshot": {
        "id": "f30f7139-ef61-4fbd-9bf1-62199e762f8f",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-de715913057d/f30f7139-ef61-4fbd-9bf1-62199e762f8f-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-de715913057d/f30f7139-ef61-4fbd-9bf1-62199e762f8f-hero.png",
        "page_text": {
          "cta_text": "Registruotis",
          "headline": "KEISK SAVO ĮPROČIUS IR GYVENK AKTYVIAU SU „NEPTŪNU“!",
          "full_text": "Skip to content Mūsų prekių ženklai Sužinokite Pasaulio taurė su „Coca‑Cola“ Laimėk, ką nori Wanta Fanta! SPRITE SUMMER „Fuzetea – experience everyday“ Pasinaudok proga pasikeisti su „Neptūnu“ Lidl loterija Peržiūrėti viską Poveikis Tvarumas Socialinė veikla Sveikata ir gerovė Programėlės puslapis Registruotis Registruotis Prisijungti Registruotis Account Menu Pasinaudok proga pasikeisti su „Neptūnu“ Taisyklės KEISK SAVO ĮPROČIUS IR GYVENK AKTYVIAU SU „NEPTŪNU“! Judėti daugiau ir gyventi aktyviau – visada gera idėja. „Neptūno“ kampanijos prizai p",
          "subheadline": "",
          "pricing_tiers": []
        },
        "pixel_diff_pct": null,
        "has_meaningful_change": false,
        "change_analysis": {},
        "taken_at": "2026-07-06T18:05:34.447318+00:00",
        "status": "ok"
      }
    },
    "stats": {
      "totalSnapshots": 1,
      "changeCount": 0,
      "firstSnapshotAt": "2026-07-06T18:05:34.447318+00:00",
      "lastSnapshotAt": "2026-07-06T18:05:34.447318+00:00"
    },
    "snapshots": [
      {
        "id": "f30f7139-ef61-4fbd-9bf1-62199e762f8f",
        "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-de715913057d/f30f7139-ef61-4fbd-9bf1-62199e762f8f-full.png",
        "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-de715913057d/f30f7139-ef61-4fbd-9bf1-62199e762f8f-hero.png",
        "page_text": {
          "cta_text": "Registruotis",
          "headline": "KEISK SAVO ĮPROČIUS IR GYVENK AKTYVIAU SU „NEPTŪNU“!",
          "full_text": "Skip to content Mūsų prekių ženklai Sužinokite Pasaulio taurė su „Coca‑Cola“ Laimėk, ką nori Wanta Fanta! SPRITE SUMMER „Fuzetea – experience everyday“ Pasinaudok proga pasikeisti su „Neptūnu“ Lidl loterija Peržiūrėti viską Poveikis Tvarumas Socialinė veikla Sveikata ir gerovė Programėlės puslapis Registruotis Registruotis Prisijungti Registruotis Account Menu Pasinaudok proga pasikeisti su „Neptūnu“ Taisyklės KEISK SAVO ĮPROČIUS IR GYVENK AKTYVIAU SU „NEPTŪNU“! Judėti daugiau ir gyventi aktyviau – visada gera idėja. „Neptūno“ kampanijos prizai p",
          "subheadline": "",
          "pricing_tiers": []
        },
        "pixel_diff_pct": null,
        "has_meaningful_change": false,
        "change_analysis": {},
        "taken_at": "2026-07-06T18:05:34.447318+00:00",
        "status": "ok"
      }
    ]
  }
} as Record<string, PageDetailStaticPayload>;

export const FROZEN_LANDING_PAGE_CHANGES: DemoLandingPageChangeRow[] = [
  {
    "id": "aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc",
    "screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc-full.png",
    "hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/aa8f7945-ebf8-44aa-8d69-be3e5bc11bcc-hero.png",
    "page_text": {
      "cta_text": "Contact us",
      "headline": "Competitor spying on autopilot",
      "full_text": "Competitor spying on autopilot Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes. Contact us paid ads organic email connected into one dashboard",
      "subheadline": "Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform."
    },
    "pixel_diff_pct": 10.11,
    "has_meaningful_change": true,
    "change_analysis": {
      "urgency": "high",
      "what_to_do": "Run a test adding a 'Contact us' or 'Book a demo' secondary CTA alongside your existing 'TRY FOR FREE' button — Rival should capture enterprise-intent visitors without abandoning the self-serve funnel that Neptunas appears to be walking away from, creating an opportunity to win SMB and mid-market users that Neptunas is deprioritizing.",
      "threat_score": 7,
      "what_changed": "1. Hero CTA button changed from 'TRY FOR FREE' to 'Contact us' — both in the nav and the main hero button. 2. Hero background changed from a blue gradient to a light grey/white gradient. 3. The feature cards row below the hero (Paid ads, Organic, Email, Autopilot, MCP with checkmarks) was replaced with a new icon row showing individual platform logos grouped by category (paid ads: Meta, Google, TikTok, LinkedIn, Pinterest, Snapchat; organic: Instagram, TikTok, YouTube, LinkedIn, X; email: envelope icon) with a 'connected into one dashboard' label. 4. Headline capitalization changed from all-lowercase 'competitor spying on autopilot' to title-case 'Competitor spying on autopilot'. 5. At y=8800, the previous section showed a three-column pricing grid (Starter $40, Pro $60, Agency $100) with 'TRY FOR FREE' buttons. The new section at y=8800 shows an Enterprise plan with 'Custom pricing' and 'Volume-based · annual contracts available' — the self-serve pricing tiers are no longer visible at this scroll depth, replaced by an enterprise-focused card.",
      "visual_changes": [
        {
          "id": "region_1",
          "label": "Hero section",
          "section": "hero",
          "after_color": "#edf3f9",
          "before_color": "#e1e7ec",
          "color_changed": true,
          "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_1.png",
          "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_1.png"
        },
        {
          "id": "region_2",
          "label": "Pricing section",
          "section": "pricing",
          "after_color": "#9eb9c8",
          "before_color": "#a9c0ce",
          "color_changed": true,
          "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_2.png",
          "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_2.png"
        },
        {
          "id": "region_3",
          "label": "Hero section",
          "section": "hero",
          "after_color": "#e5e8ef",
          "before_color": "#b8cee0",
          "color_changed": true,
          "after_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_after_region_3.png",
          "before_crop_url": "https://dbcfxoxanvdbghemlaya.supabase.co/storage/v1/object/public/landing-page-screenshots/2d67a049-dde5-40bc-92ec-ee43411e3bbb/b604c557-dc24-4664-a95f-2c99fb3194ca/rival/2026-07-15T02-03-56_diff_before_region_3.png"
        }
      ],
      "mask_overlap_pct": 0,
      "sections_changed": [
        "hero",
        "pricing",
        "cta",
        "nav"
      ],
      "change_confidence": "confirmed",
      "ignored_animation": false,
      "strategic_interpretation": "This is a significant strategic pivot from a self-serve PLG (product-led growth) motion to an enterprise/sales-led motion. Removing 'TRY FOR FREE' and replacing it with 'Contact us' signals they are no longer acquiring users through a free trial funnel — they want inbound sales conversations instead. The pricing section shift toward Enterprise/Custom pricing reinforces this: they may have found that free trial users churned quickly or had low LTV, and are repositioning toward larger accounts (agencies, growth teams) that convert better through sales. The platform logo grid replaces the feature card checklist, likely to visually communicate breadth of coverage more quickly to enterprise buyers evaluating integrations. This could also mean they are testing whether a sales-qualified lead flow converts better than self-serve signups."
    },
    "taken_at": "2026-07-15T02:05:06.849035+00:00",
    "status": "ok",
    "landing_pages": {
      "id": "fp-cbeaf8bff094",
      "label": "Rival",
      "url": "spyrival.com",
      "page_type": "custom"
    },
    "prev_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/ef88aba3-8119-48b7-8a9c-eb4f7933c9ea-full.png",
    "prev_hero_screenshot_url": "/demo/frozen/neptunas.lt/pages/fp-cbeaf8bff094/ef88aba3-8119-48b7-8a9c-eb4f7933c9ea-hero.png",
    "prev_page_text": {
      "cta_text": "TRY FOR FREE",
      "headline": "competitor spying on autopilot",
      "full_text": "competitor spying on autopilot\n\nCompetitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.Track competitor ads, organic social, and email in one platform - ad libraries, strategy maps, and alerts when something changes.\n\nTRY FOR FREE\n\n- Paid ads\n\n- Organic\n\n- Email\n\n- Autopilot\n\n- MCP",
      "subheadline": "Competitor ads, organic, and email - ad libraries, strategy maps, and alerts in one platform.",
      "pricing_tiers": []
    },
    "prev_taken_at": "2026-07-07T08:15:20.049143+00:00"
  }
] as DemoLandingPageChangeRow[];
