/* eslint-disable */
/** AUTO-GENERATED by scripts/freeze-demo-ad-creatives.ts — do not edit by hand. */

import type { DemoCreativeTest } from "@/lib/demo/dashboard-demo-data";
import type { TimelineAd } from "@/components/competitor/tests-timeline/timeline-types";

export type FrozenScrapedAd = {
  id: string;
  platform: string;
  format: string;
  ad_text: string;
  ai_extracted_angle: string | null;
  first_seen_at: string;
  last_seen_at: string;
  is_active: boolean;
  frozen_creative_url: string;
};

export const FROZEN_ADS_SOURCE_SLUG = "nike.com";
export const FROZEN_ADS_BRAND_NAME = "Nike";

export const FROZEN_AD_BY_ID: Record<string, FrozenScrapedAd> = {
  "b05cf74e-b11b-42ef-babc-f64d5bad5b37": {
    "id": "b05cf74e-b11b-42ef-babc-f64d5bad5b37",
    "platform": "meta",
    "format": "image",
    "ad_text": "Hazte miembro Nike y obtén beneficios especiales como MSI con tarjetas participantes 👏   Consulta Términos y Condiciones\nNike\nUnlock the latest from Nike & Jordan. Shop sneakers & apparel for all athletes.\nInstall Now",
    "ai_extracted_angle": "social_proof · Hook: Nike Member: Beneficios especiales y MSI · Body: Membership benefits and flexible payment options",
    "first_seen_at": "2025-10-08T07:00:00+00:00",
    "last_seen_at": "2026-07-04T14:09:54.373+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/b05cf74e-b11b-42ef-babc-f64d5bad5b37.jpg"
  },
  "76e9f9ab-5992-4185-8f08-5ab120cb107f": {
    "id": "76e9f9ab-5992-4185-8f08-5ab120cb107f",
    "platform": "meta",
    "format": "image",
    "ad_text": "Celebra tu cumpleaños con Nike y obtén acceso a productos exclusivos, MSI, envío y devoluciones gratis el resto del año.\nEspinillera de fútbol Nike Charge - Blanco\nThe latest macOS offers the world’s best way to play — and add to — your collection of music, movies, TV shows, pod…",
    "ai_extracted_angle": "discount · Hook: Celebra tu cumpleaños con Nike · Body: Birthday exclusive benefits and perks",
    "first_seen_at": "2026-04-07T07:00:00+00:00",
    "last_seen_at": "2026-07-04T14:09:54.373+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/76e9f9ab-5992-4185-8f08-5ab120cb107f.jpg"
  },
  "9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa": {
    "id": "9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa",
    "platform": "meta",
    "format": "image",
    "ad_text": "Celebra tu cumpleaños con Nike y obtén acceso a productos exclusivos, MSI, envío y devoluciones gratis el resto del año.\nGoogles Nike Swim Hyper Flow - Gris\nEnjoy millions of the latest Android apps, games, music, movies, TV, books, magazines & more. Anytime, anywhere, across yo…",
    "ai_extracted_angle": "discount · Hook: Birthday exclusive: Free shipping & returns all year · Body: Birthday membership offer with product showcase",
    "first_seen_at": "2026-03-31T07:00:00+00:00",
    "last_seen_at": "2026-07-04T14:09:54.373+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa.jpg"
  },
  "c3401f3c-6643-488b-bb7f-1fe191ee3ec4": {
    "id": "c3401f3c-6643-488b-bb7f-1fe191ee3ec4",
    "platform": "google",
    "format": "text",
    "ad_text": "Nike Retail BV — nike.com\nSearch / text · Shown 2025-10-22 → 2026-07-03\n2025-10-22 – 2026-07-03",
    "ai_extracted_angle": "brand awareness · Hook: Nike Retail BV · Body: Brand listing on Google search",
    "first_seen_at": "2025-10-22T00:00:00+00:00",
    "last_seen_at": "2026-07-03T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/c3401f3c-6643-488b-bb7f-1fe191ee3ec4.png"
  },
  "66886bc3-6589-4403-bd09-53bd369c6b69": {
    "id": "66886bc3-6589-4403-bd09-53bd369c6b69",
    "platform": "google",
    "format": "text",
    "ad_text": "Nike Retail BV — nike.com\nSearch / text · Shown 2025-10-24 → 2026-07-03\n2025-10-24 – 2026-07-03",
    "ai_extracted_angle": "brand awareness · Hook: Nike Retail BV · Body: Brand listing on Google search",
    "first_seen_at": "2025-10-24T00:00:00+00:00",
    "last_seen_at": "2026-07-03T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/66886bc3-6589-4403-bd09-53bd369c6b69.png"
  },
  "6a98a255-6c20-4d08-9876-71bfc6073907": {
    "id": "6a98a255-6c20-4d08-9876-71bfc6073907",
    "platform": "google",
    "format": "text",
    "ad_text": "Nike Retail BV — nike.com\nSearch / text · Shown 2025-10-22 → 2026-07-03\n2025-10-22 – 2026-07-03",
    "ai_extracted_angle": "brand awareness · Hook: Nike Retail BV · Body: Brand listing on Google search",
    "first_seen_at": "2025-10-22T00:00:00+00:00",
    "last_seen_at": "2026-07-03T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/6a98a255-6c20-4d08-9876-71bfc6073907.png"
  },
  "e598ee76-f76c-41ad-a9eb-bd6600b8c4f2": {
    "id": "e598ee76-f76c-41ad-a9eb-bd6600b8c4f2",
    "platform": "pinterest",
    "format": "image",
    "ad_text": "Nike AeroSwift BTC\nMit diesem schmal geschnittenen Nike AeroSwift Singlet bist du stets laufbereit und kannst bei deinem nächsten Lauf optimale Leistung bringen. Das fortschrittliche, feuchtigkeitsableitende Material mit strategisch platzierter Belüftung hält dich angenehm kühl,…",
    "ai_extracted_angle": "quality · Hook: Nike AeroSwift BTC - Laufbereit · Body: Performance and innovation for runners",
    "first_seen_at": "2026-05-02T00:00:00+00:00",
    "last_seen_at": "2026-06-23T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/e598ee76-f76c-41ad-a9eb-bd6600b8c4f2.jpg"
  },
  "6dc763b3-d408-403f-9398-fc15962fbda0": {
    "id": "6dc763b3-d408-403f-9398-fc15962fbda0",
    "platform": "pinterest",
    "format": "image",
    "ad_text": "Luka Dončić Los Angeles\nHol dir einen Look, der von den Profis inspiriert wurde. Die Farben und Logos der Lakers passen zu dem, was Luka Dončić auf dem Court trägt.",
    "ai_extracted_angle": "identity · Hook: Luka Dončić Lakers Look · Body: Pro-inspired fan gear",
    "first_seen_at": "2026-05-02T00:00:00+00:00",
    "last_seen_at": "2026-06-23T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/6dc763b3-d408-403f-9398-fc15962fbda0.jpg"
  },
  "37812ba6-93d1-4198-a4c2-4b1383d49c52": {
    "id": "37812ba6-93d1-4198-a4c2-4b1383d49c52",
    "platform": "pinterest",
    "format": "image",
    "ad_text": "Cameron Johnson Brooklyn\nDas Brooklyn Nets City Edition Trikot 2025/26 ist eine kühne Neuinterpretation eines Fan-Favoriten: der City Edition 2018/19. Es ist eine Hommage an die Farben, die Brooklyns Lebendigkeit zum ersten Mal auf das Spielfeld gebracht haben und nun für eine n…",
    "ai_extracted_angle": "curiosity · Hook: Cameron Johnson Brooklyn Nets City Edition · Body: Design narrative and city homage",
    "first_seen_at": "2026-05-02T00:00:00+00:00",
    "last_seen_at": "2026-06-23T00:00:00+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/37812ba6-93d1-4198-a4c2-4b1383d49c52.jpg"
  },
  "6905d147-c61b-4e97-9076-11f95626f1e1": {
    "id": "6905d147-c61b-4e97-9076-11f95626f1e1",
    "platform": "snapchat",
    "format": "image",
    "ad_text": "unreal motion powered by 8\nACTIVE · Review: APPROVED",
    "ai_extracted_angle": "Motion/animation technology showcase · Hook: Unreal motion powered by 8 · Body: Tech-driven creative tool awareness",
    "first_seen_at": "2026-05-14T21:45:09.07+00:00",
    "last_seen_at": "2026-05-21T16:49:39.026+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/6905d147-c61b-4e97-9076-11f95626f1e1.png"
  },
  "2c7395f1-8645-4200-9fe9-d71139487aac": {
    "id": "2c7395f1-8645-4200-9fe9-d71139487aac",
    "platform": "snapchat",
    "format": "image",
    "ad_text": "unreal motion powered by 8\nACTIVE · Review: APPROVED",
    "ai_extracted_angle": "Brand/product teaser - insufficient copy · Hook: Unreal motion powered by 8 · Body: Brand awareness / product discovery",
    "first_seen_at": "2026-05-21T13:47:40.219+00:00",
    "last_seen_at": "2026-05-21T16:49:39.026+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/2c7395f1-8645-4200-9fe9-d71139487aac.png"
  },
  "a2e02faf-2be9-486e-8dd3-9d38c29c0a22": {
    "id": "a2e02faf-2be9-486e-8dd3-9d38c29c0a22",
    "platform": "snapchat",
    "format": "image",
    "ad_text": "unreal motion powered by 8\nACTIVE · Review: APPROVED",
    "ai_extracted_angle": "curiosity · Hook: Unreal motion powered by 8 · Body: Tech product awareness or brand discovery",
    "first_seen_at": "2026-05-21T13:47:40.219+00:00",
    "last_seen_at": "2026-05-21T16:49:39.026+00:00",
    "is_active": true,
    "frozen_creative_url": "/demo/frozen/nike.com/ads/a2e02faf-2be9-486e-8dd3-9d38c29c0a22.png"
  }
} as Record<string, FrozenScrapedAd>;

export const FROZEN_LIBRARY_AD_IDS: string[] = [
  "b05cf74e-b11b-42ef-babc-f64d5bad5b37",
  "76e9f9ab-5992-4185-8f08-5ab120cb107f",
  "9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa",
  "c3401f3c-6643-488b-bb7f-1fe191ee3ec4",
  "66886bc3-6589-4403-bd09-53bd369c6b69",
  "6a98a255-6c20-4d08-9876-71bfc6073907",
  "e598ee76-f76c-41ad-a9eb-bd6600b8c4f2",
  "6dc763b3-d408-403f-9398-fc15962fbda0",
  "37812ba6-93d1-4198-a4c2-4b1383d49c52"
];

export const FROZEN_TIMELINE_AD_IDS: string[] = [
  "b05cf74e-b11b-42ef-babc-f64d5bad5b37",
  "76e9f9ab-5992-4185-8f08-5ab120cb107f",
  "9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa",
  "c3401f3c-6643-488b-bb7f-1fe191ee3ec4",
  "66886bc3-6589-4403-bd09-53bd369c6b69"
];

export const FROZEN_TIMELINE_ADS: TimelineAd[] = [
  {
    "id": "b05cf74e-b11b-42ef-babc-f64d5bad5b37",
    "platform": "meta",
    "ad_creative_url": "/demo/frozen/nike.com/ads/b05cf74e-b11b-42ef-babc-f64d5bad5b37.jpg",
    "archived_creative_url": "/demo/frozen/nike.com/ads/b05cf74e-b11b-42ef-babc-f64d5bad5b37.jpg",
    "ad_text": "Hazte miembro Nike y obtén beneficios especiales como MSI con tarjetas participantes 👏   Consulta Términos y Condiciones\nNike\nUnlock the latest from Nike & Jordan. Shop sneakers & apparel for all athletes.\nInstall Now",
    "ai_extracted_angle": "social_proof · Hook: Nike Member: Beneficios especiales y MSI · Body: Membership benefits and flexible payment options",
    "first_seen_at": "2025-10-08T07:00:00+00:00",
    "last_seen_at": "2026-07-04T14:09:54.373+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "76e9f9ab-5992-4185-8f08-5ab120cb107f",
    "platform": "meta",
    "ad_creative_url": "/demo/frozen/nike.com/ads/76e9f9ab-5992-4185-8f08-5ab120cb107f.jpg",
    "archived_creative_url": "/demo/frozen/nike.com/ads/76e9f9ab-5992-4185-8f08-5ab120cb107f.jpg",
    "ad_text": "Celebra tu cumpleaños con Nike y obtén acceso a productos exclusivos, MSI, envío y devoluciones gratis el resto del año.\nEspinillera de fútbol Nike Charge - Blanco\nThe latest macOS offers the world’s best way to play — and add to — your collection of music, movies, TV shows, pod…",
    "ai_extracted_angle": "discount · Hook: Celebra tu cumpleaños con Nike · Body: Birthday exclusive benefits and perks",
    "first_seen_at": "2026-04-07T07:00:00+00:00",
    "last_seen_at": "2026-07-04T14:09:54.373+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa",
    "platform": "meta",
    "ad_creative_url": "/demo/frozen/nike.com/ads/9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa.jpg",
    "archived_creative_url": "/demo/frozen/nike.com/ads/9bf9bf14-4a6b-43b1-9051-b8cdc6e49ffa.jpg",
    "ad_text": "Celebra tu cumpleaños con Nike y obtén acceso a productos exclusivos, MSI, envío y devoluciones gratis el resto del año.\nGoogles Nike Swim Hyper Flow - Gris\nEnjoy millions of the latest Android apps, games, music, movies, TV, books, magazines & more. Anytime, anywhere, across yo…",
    "ai_extracted_angle": "discount · Hook: Birthday exclusive: Free shipping & returns all year · Body: Birthday membership offer with product showcase",
    "first_seen_at": "2026-03-31T07:00:00+00:00",
    "last_seen_at": "2026-07-04T14:09:54.373+00:00",
    "format": "image",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "c3401f3c-6643-488b-bb7f-1fe191ee3ec4",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/nike.com/ads/c3401f3c-6643-488b-bb7f-1fe191ee3ec4.png",
    "archived_creative_url": "/demo/frozen/nike.com/ads/c3401f3c-6643-488b-bb7f-1fe191ee3ec4.png",
    "ad_text": "Nike Retail BV — nike.com\nSearch / text · Shown 2025-10-22 → 2026-07-03\n2025-10-22 – 2026-07-03",
    "ai_extracted_angle": "brand awareness · Hook: Nike Retail BV · Body: Brand listing on Google search",
    "first_seen_at": "2025-10-22T00:00:00+00:00",
    "last_seen_at": "2026-07-03T00:00:00+00:00",
    "format": "text",
    "is_winner": false,
    "is_killed": false
  },
  {
    "id": "66886bc3-6589-4403-bd09-53bd369c6b69",
    "platform": "google",
    "ad_creative_url": "/demo/frozen/nike.com/ads/66886bc3-6589-4403-bd09-53bd369c6b69.png",
    "archived_creative_url": "/demo/frozen/nike.com/ads/66886bc3-6589-4403-bd09-53bd369c6b69.png",
    "ad_text": "Nike Retail BV — nike.com\nSearch / text · Shown 2025-10-24 → 2026-07-03\n2025-10-24 – 2026-07-03",
    "ai_extracted_angle": "brand awareness · Hook: Nike Retail BV · Body: Brand listing on Google search",
    "first_seen_at": "2025-10-24T00:00:00+00:00",
    "last_seen_at": "2026-07-03T00:00:00+00:00",
    "format": "text",
    "is_winner": false,
    "is_killed": false
  }
] as TimelineAd[];

export const FROZEN_CREATIVE_TESTS: DemoCreativeTest[] = [] as DemoCreativeTest[];

export function getFrozenCreativeUrl(adId: string): string | null {
  return FROZEN_AD_BY_ID[adId]?.frozen_creative_url ?? null;
}
