/* eslint-disable */
/** AUTO-GENERATED by scripts/freeze-demo-organic.ts — do not edit by hand. */

export type FrozenOrganicPost = {
  id: string;
  platform: string;
  content: string;
  likes: number;
  comments: number;
  views?: number;
  postedAt: string;
  previewUrl: string | null;
  gradient: string;
  isVideo?: boolean;
};

export const FROZEN_ORGANIC_SOURCE_SLUG = "nike.com";
export const FROZEN_ORGANIC_BRAND_NAME = "Nike";

export const FROZEN_ORGANIC_POSTS: FrozenOrganicPost[] = [
  {
    "id": "8e8c8a07-1dc7-4d63-aad8-5cd9fa49ea73",
    "platform": "instagram",
    "content": "Nike Atelier for Victor Wembanyama is shaped by instinct and precision, through a distinctly French lens. Football heritage, reimagined. Ex…",
    "likes": 94368,
    "comments": 354,
    "postedAt": "1d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/8e8c8a07-1dc7-4d63-aad8-5cd9fa49ea73.jpg",
    "gradient": "linear-gradient(135deg, #fdf2f8 0%, #f472b6 50%, #7c3aed 100%)",
    "isVideo": false
  },
  {
    "id": "b9b1196c-7505-4547-b2d5-499fd996db72",
    "platform": "youtube",
    "content": "Nike Sabrina 4 | Play Fast. Play Free. Play Light.",
    "likes": 87,
    "comments": 3,
    "views": 3730,
    "postedAt": "1d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/b9b1196c-7505-4547-b2d5-499fd996db72.jpg",
    "gradient": "linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #f87171 100%)",
    "isVideo": false
  },
  {
    "id": "2faa71aa-18f8-4274-b027-152041ea6929",
    "platform": "instagram",
    "content": "Always was, always will be. World No. 1 @janniksin leaves no doubt as he takes a second consecutive title in London.",
    "likes": 231820,
    "comments": 816,
    "postedAt": "2d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/2faa71aa-18f8-4274-b027-152041ea6929.jpg",
    "gradient": "linear-gradient(135deg, #fdf2f8 0%, #f472b6 50%, #7c3aed 100%)",
    "isVideo": false
  },
  {
    "id": "45524dc8-4b76-49d2-9180-0eaefd5a9d0a",
    "platform": "instagram",
    "content": "@erling’s hunt never ends.",
    "likes": 142468,
    "comments": 1036,
    "postedAt": "3d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/45524dc8-4b76-49d2-9180-0eaefd5a9d0a.jpg",
    "gradient": "linear-gradient(135deg, #fdf2f8 0%, #f472b6 50%, #7c3aed 100%)",
    "isVideo": false
  },
  {
    "id": "31e219bf-cb65-4ea7-8d31-8b8ab71508c4",
    "platform": "instagram",
    "content": "@tokitoistheone and @nielsvink are making a habit out of making history. Tokito defends his turf with back to back titles in London. Niels…",
    "likes": 24570,
    "comments": 55,
    "postedAt": "3d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/31e219bf-cb65-4ea7-8d31-8b8ab71508c4.jpg",
    "gradient": "linear-gradient(135deg, #fdf2f8 0%, #f472b6 50%, #7c3aed 100%)",
    "isVideo": false
  },
  {
    "id": "529a4e45-967b-4154-9195-a43aa7c76816",
    "platform": "linkedin",
    "content": "The best innovation solves real athlete problems. Nike Aero-FIT is our first elite performance apparel made from 100% textile waste, engine…",
    "likes": 437,
    "comments": 21,
    "postedAt": "4d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/529a4e45-967b-4154-9195-a43aa7c76816.jpg",
    "gradient": "linear-gradient(135deg, #0a2540 0%, #0a66c2 55%, #70b5f9 100%)",
    "isVideo": false
  },
  {
    "id": "5a4134a6-0ab6-4538-9be6-fc9f37fc527c",
    "platform": "linkedin",
    "content": "One year in. Six continents. 25 cities. 10,000 kids who proved the beautiful game belongs to everyone. ⚽🔥 Toma el Juego, Nike’s global str…",
    "likes": 441,
    "comments": 20,
    "postedAt": "7d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/5a4134a6-0ab6-4538-9be6-fc9f37fc527c.jpg",
    "gradient": "linear-gradient(135deg, #0a2540 0%, #0a66c2 55%, #70b5f9 100%)",
    "isVideo": false
  },
  {
    "id": "86af34b5-075b-42e5-b376-643eb89cd614",
    "platform": "instagram",
    "content": "The story continues @cristiano",
    "likes": 1861326,
    "comments": 16148,
    "postedAt": "8d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/86af34b5-075b-42e5-b376-643eb89cd614.jpg",
    "gradient": "linear-gradient(135deg, #fdf2f8 0%, #f472b6 50%, #7c3aed 100%)",
    "isVideo": false
  },
  {
    "id": "cbe43394-d6fc-4388-9181-1ec1632fad94",
    "platform": "tiktok",
    "content": "Core memories with tour reigning queens of track and field. Shot in Los Angeles for the After Dark Tour.",
    "likes": 1077,
    "comments": 130,
    "views": 85500,
    "postedAt": "12d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/cbe43394-d6fc-4388-9181-1ec1632fad94.jpg",
    "gradient": "linear-gradient(160deg, #0f172a 0%, #334155 45%, #64748b 100%)",
    "isVideo": true
  },
  {
    "id": "52902e77-5aa1-479e-95b3-ae1c22b658e5",
    "platform": "tiktok",
    "content": "@FaithKipyegon and @Keely don't chase limits -they redefine them. Shot in Los Angeles for the After Dark Tour.",
    "likes": 1552,
    "comments": 62,
    "views": 83100,
    "postedAt": "13d ago",
    "previewUrl": "/demo/frozen/nike.com/organic/52902e77-5aa1-479e-95b3-ae1c22b658e5.jpg",
    "gradient": "linear-gradient(160deg, #0f172a 0%, #334155 45%, #64748b 100%)",
    "isVideo": true
  }
];

export const FROZEN_ORGANIC_HANDLES = {
  "instagram": "@nike",
  "tiktok": "@nike",
  "youtube": "https://www.youtube.com/@nike",
  "linkedin": "https://www.linkedin.com/company/nike",
  "x": "@nike",
  "facebook": "https://www.facebook.com/nike"
};
