/* eslint-disable */
/** AUTO-GENERATED by scripts/freeze-demo-brand-logos.ts — do not edit by hand. */

export const FROZEN_DEMO_BRAND_LOGOS = {
  "adidas.com": {
    name: "Adidas",
    logoUrl: "/demo/frozen/adidas.com/logo.jpg",
    sourceUrl: "https://preview.thenewsmarket.com/Previews/ADID/StillAssets/960x540/689347.jpg",
  },
  "nike.com": {
    name: "Nike",
    logoUrl: "/demo/frozen/nike.com/logo.png",
    sourceUrl: "https://www.google.com/s2/favicons?domain=nike.com&sz=128",
  }
} as const;

export type FrozenDemoBrandSlug = keyof typeof FROZEN_DEMO_BRAND_LOGOS;
