/**
 * Freeze competitor brand logos from saved_competitors into static demo assets.
 *
 * Usage:
 *   npx tsx scripts/freeze-demo-brand-logos.ts --user-email=attributo@yahoo.com
 */
import { config } from "dotenv";

config({ path: ".env.local" });

import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import { createSupabaseAdminClient } from "../src/lib/supabase/admin";

const WEB_ROOT = process.cwd();
const FROZEN_PUBLIC = path.join(WEB_ROOT, "public", "demo", "frozen");
const FROZEN_LIB = path.join(WEB_ROOT, "src", "lib", "demo", "frozen");

const DEMO_BRAND_SLUGS = ["adidas.com", "nike.com"] as const;

function extFromContentType(ct: string | null, url: string): string {
  const lower = (ct ?? "").toLowerCase();
  if (lower.includes("webp")) return ".webp";
  if (lower.includes("png")) return ".png";
  if (lower.includes("jpeg") || lower.includes("jpg")) return ".jpg";
  if (lower.includes("svg")) return ".svg";
  if (lower.includes("ico") || lower.includes("icon")) return ".ico";
  if (url.includes(".webp")) return ".webp";
  if (url.includes(".png")) return ".png";
  if (url.includes(".jpg") || url.includes(".jpeg")) return ".jpg";
  if (url.includes(".svg")) return ".svg";
  return ".png";
}

async function resolveUserId(admin: ReturnType<typeof createSupabaseAdminClient>, email: string) {
  const { data: users } = await admin.auth.admin.listUsers({ perPage: 500 });
  const match = users?.users?.find((u) => u.email?.toLowerCase() === email.toLowerCase());
  if (!match) throw new Error(`No user found for email: ${email}`);
  return match.id;
}

async function downloadLogo(remoteUrl: string, slug: string): Promise<string> {
  const res = await fetch(remoteUrl, { redirect: "follow" });
  if (!res.ok) {
    throw new Error(`Failed to download logo (${res.status}) for ${slug}: ${remoteUrl}`);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  const ext = extFromContentType(res.headers.get("content-type"), remoteUrl);
  const rel = path.join(slug, `logo${ext}`);
  const finalPath = path.join(FROZEN_PUBLIC, rel);
  await fs.mkdir(path.dirname(finalPath), { recursive: true });
  await fs.writeFile(finalPath, buf);
  return `/demo/frozen/${rel.split(path.sep).join("/")}`;
}

async function main() {
  const userEmail =
    process.argv.find((a) => a.startsWith("--user-email="))?.slice("--user-email=".length).trim() ??
    "attributo@yahoo.com";

  const admin = createSupabaseAdminClient();
  const userId = await resolveUserId(admin, userEmail);

  const frozen: Record<string, { name: string; logoUrl: string; sourceUrl: string }> = {};

  for (const slug of DEMO_BRAND_SLUGS) {
    const { data, error } = await admin
      .from("saved_competitors")
      .select("id, name, slug, logo_url, brand_logo_url")
      .eq("slug", slug)
      .eq("user_id", userId)
      .maybeSingle();
    if (error) throw error;
    if (!data) throw new Error(`No competitor for slug=${slug}`);

    const sourceUrl = (data.brand_logo_url ?? data.logo_url)?.trim();
    if (!sourceUrl) throw new Error(`No logo_url for slug=${slug}`);

    console.log(`Freezing ${slug} logo from ${sourceUrl}`);
    const logoUrl = await downloadLogo(sourceUrl, slug);
    frozen[slug] = { name: data.name, logoUrl, sourceUrl };
  }

  const outPath = path.join(FROZEN_LIB, "frozen-demo-brand-logos.ts");
  const body = `/* eslint-disable */
/** AUTO-GENERATED by scripts/freeze-demo-brand-logos.ts — do not edit by hand. */

export const FROZEN_DEMO_BRAND_LOGOS = {
${DEMO_BRAND_SLUGS.map(
  (slug) =>
    `  ${JSON.stringify(slug)}: {\n    name: ${JSON.stringify(frozen[slug]!.name)},\n    logoUrl: ${JSON.stringify(frozen[slug]!.logoUrl)},\n    sourceUrl: ${JSON.stringify(frozen[slug]!.sourceUrl)},\n  }`,
).join(",\n")}
} as const;

export type FrozenDemoBrandSlug = keyof typeof FROZEN_DEMO_BRAND_LOGOS;
`;
  await fs.writeFile(outPath, body);

  const manifestPath = path.join(FROZEN_PUBLIC, "manifest.json");
  let manifest: Record<string, unknown> = {};
  try {
    manifest = JSON.parse(await fs.readFile(manifestPath, "utf8")) as Record<string, unknown>;
  } catch {
    manifest = {};
  }
  manifest.brandLogos = {
    frozenAt: new Date().toISOString(),
    slugs: DEMO_BRAND_SLUGS,
    checksum: createHash("sha256")
      .update(DEMO_BRAND_SLUGS.map((slug) => frozen[slug]!.logoUrl).join("|"))
      .digest("hex")
      .slice(0, 16),
  };
  await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  console.log(`Wrote ${outPath}`);
  for (const slug of DEMO_BRAND_SLUGS) {
    console.log(`  ${slug} → ${frozen[slug]!.logoUrl}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
