import type { TimelineAd } from "@/components/competitor/tests-timeline/timeline-types";
import type {
  DemoAd,
  DemoCreativeTest,
  DemoPlatform,
} from "@/lib/demo/dashboard-demo-data";
import { DEMO_OWN_BRAND } from "@/lib/demo/dashboard-demo-config";
import type {
  FunnelCellId,
  FunnelCellNodePayload,
  FunnelStage,
  StrategyChannelSignals,
  StrategyJourneyGoal,
  StrategyMapPayload,
  StrategyPlatform,
} from "@/lib/strategy-overview/payload-types";

export const OWN_PLATFORM_ACTIVE_COUNTS: Record<DemoPlatform, number> = {
  meta: 38,
  google: 22,
  tiktok: 6,
  linkedin: 4,
  pinterest: 3,
  snapchat: 3,
};

export const OWN_PLATFORM_TOTAL_COUNTS: Record<DemoPlatform, number> = {
  meta: 48,
  google: 28,
  tiktok: 8,
  linkedin: 6,
  pinterest: 4,
  snapchat: 4,
};

export const OWN_ACTIVITY_SCORE = {
  score: 52,
  tier: 3,
  tierLabel: "Tier 3",
  spend: "~€3K–€8K/mo in this market",
  confidence: "High confidence",
  topPercent: "TOP 35%",
  reasons: [
    "Focused Meta + Google testing cadence",
    "Clear product-led messaging on landing pages",
    "Smaller but efficient multi-channel footprint",
  ],
} as const;

export const OWN_LANDING_PAGES = [
  { id: "own-lp-1", url: "your-brand.com/pricing", ads: 64, platforms: { meta: 38, google: 26 } },
  { id: "own-lp-2", url: "your-brand.com/features", ads: 38, platforms: { meta: 22, google: 16 } },
  { id: "own-lp-3", url: "your-brand.com/demo", ads: 22, platforms: { meta: 14, google: 8 } },
  { id: "own-lp-4", url: "your-brand.com/blog", ads: 15, platforms: { meta: 9, linkedin: 6 } },
] as const;

export const OWN_SAVED_AD = {
  id: "own-saved-1",
  title: "product-led • Hook: See your rivals' ads in one dashboard",
  body: "Long-running TOF creative promoting the competitive intelligence workspace.",
  savedAt: "Jun 18, 2026",
  gradient: "linear-gradient(135deg, #e0f2fe 0%, #bae6fd 50%, #0ea5e9 100%)",
} as const;

export const OWN_ADS: DemoAd[] = [
  {
    id: "own-meta-1",
    platform: "meta",
    pageName: DEMO_OWN_BRAND.name,
    body: "Ship faster with one workspace for creative, paid, and organic. Start free — no credit card.",
    headline: "Try free for 14 days",
    linkDescription: "Competitive intelligence for growth teams",
    cta: "Sign Up",
    siteLabel: "your-brand.com/pricing",
    activeDays: 18,
    gradient: "linear-gradient(135deg, #0c4a6e 0%, #0ea5e9 55%, #7dd3fc 100%)",
    funnel: "bottom",
    format: "Image",
    lifespanDays: 44,
    angle: "Free trial",
  },
  {
    id: "own-meta-2",
    platform: "meta",
    pageName: DEMO_OWN_BRAND.name,
    body: "Stop guessing what competitors launch. Get alerts when their ads, emails, and pages change.",
    headline: "Spy on rivals automatically",
    linkDescription: "Built for performance marketers",
    cta: "Learn More",
    siteLabel: "your-brand.com/features",
    activeDays: 11,
    isVideo: true,
    gradient: "linear-gradient(160deg, #082f49 0%, #0369a1 45%, #38bdf8 100%)",
    funnel: "top",
    format: "Video",
    lifespanDays: 31,
    angle: "Problem agitation",
  },
  {
    id: "own-meta-3",
    platform: "meta",
    pageName: DEMO_OWN_BRAND.name,
    body: "New: side-by-side ad libraries for up to 10 competitors. Compare angles in minutes.",
    headline: "Compare ad libraries instantly",
    linkDescription: "See a live product tour",
    cta: "Book Demo",
    siteLabel: "your-brand.com/demo",
    activeDays: 7,
    gradient: "linear-gradient(120deg, #1e3a8a 0%, #2563eb 50%, #60a5fa 100%)",
    funnel: "middle",
    format: "Image",
    lifespanDays: 21,
    angle: "Feature launch",
  },
  {
    id: "own-google-1",
    platform: "google",
    pageName: DEMO_OWN_BRAND.name,
    body: "Competitive ad intelligence software — track Meta, Google, TikTok, and email in one place.",
    headline: "Ad intelligence platform",
    linkDescription: "your-brand.com",
    cta: "Visit site",
    siteLabel: "your-brand.com",
    activeDays: 24,
    gradient: "linear-gradient(135deg, #14532d 0%, #22c55e 45%, #86efac 100%)",
    funnel: "bottom",
    format: "Search",
    lifespanDays: 58,
    angle: "Category search",
  },
  {
    id: "own-google-2",
    platform: "google",
    pageName: DEMO_OWN_BRAND.name,
    body: "See which landing pages and offers competitors push before you refresh creative.",
    headline: "Competitor landing page tracker",
    linkDescription: "Free trial available",
    cta: "Visit site",
    siteLabel: "your-brand.com/features",
    activeDays: 15,
    gradient: "linear-gradient(135deg, #052e16 0%, #16a34a 55%, #4ade80 100%)",
    funnel: "middle",
    format: "Search",
    lifespanDays: 36,
    angle: "Use case",
  },
  {
    id: "own-google-3",
    platform: "google",
    pageName: DEMO_OWN_BRAND.name,
    body: "Watch a 3-minute demo of creative tests, timelines, and strategy maps.",
    headline: "Product demo — watch now",
    linkDescription: "No signup required",
    cta: "Visit site",
    siteLabel: "your-brand.com/demo",
    activeDays: 9,
    gradient: "linear-gradient(135deg, #0f172a 0%, #334155 45%, #94a3b8 100%)",
    funnel: "middle",
    format: "Display",
    lifespanDays: 19,
    angle: "Demo CTA",
  },
  {
    id: "own-linkedin-1",
    platform: "linkedin",
    pageName: DEMO_OWN_BRAND.name,
    body: "How growth teams benchmark competitor spend without manual scraping.",
    headline: "Benchmark rivals in one dashboard",
    linkDescription: "Read the case study",
    cta: "Learn More",
    siteLabel: "your-brand.com/blog",
    activeDays: 20,
    gradient: "linear-gradient(135deg, #0a2540 0%, #0a66c2 55%, #70b5f9 100%)",
    funnel: "top",
    format: "Image",
    lifespanDays: 48,
    angle: "Thought leadership",
  },
  {
    id: "own-linkedin-2",
    platform: "linkedin",
    pageName: DEMO_OWN_BRAND.name,
    body: "Pricing built for lean teams — start at €99/mo, scale when you add competitors.",
    headline: "Transparent pricing for teams",
    linkDescription: "Compare plans",
    cta: "Sign Up",
    siteLabel: "your-brand.com/pricing",
    activeDays: 13,
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #2563eb 50%, #93c5fd 100%)",
    funnel: "bottom",
    format: "Image",
    lifespanDays: 27,
    angle: "Pricing",
  },
  {
    id: "own-linkedin-3",
    platform: "linkedin",
    pageName: DEMO_OWN_BRAND.name,
    body: "Product marketers use our workspace to spot creative tests and landing page shifts the same week they launch.",
    headline: "See rival launches the same week",
    linkDescription: "Book a demo",
    cta: "Learn More",
    siteLabel: "your-brand.com/demo",
    activeDays: 11,
    gradient: "linear-gradient(135deg, #0c4a6e 0%, #0284c7 45%, #7dd3fc 100%)",
    funnel: "middle",
    format: "Image",
    lifespanDays: 22,
    angle: "Product marketing",
  },
  {
    id: "own-tiktok-1",
    platform: "tiktok",
    pageName: DEMO_OWN_BRAND.name,
    body: "POV: you finally see every ad your competitor launches — before your Monday standup.",
    headline: "Stop manual ad library checks",
    linkDescription: "Link in bio",
    cta: "Learn More",
    siteLabel: "your-brand.com",
    activeDays: 6,
    isVideo: true,
    gradient: "linear-gradient(160deg, #0f172a 0%, #1e293b 45%, #64748b 100%)",
    funnel: "top",
    format: "Video",
    lifespanDays: 14,
    angle: "Hook / POV",
  },
  {
    id: "own-tiktok-2",
    platform: "tiktok",
    pageName: DEMO_OWN_BRAND.name,
    body: "We compared 5 rivals' Meta ads in 60 seconds. Here's what we found.",
    headline: "60-second competitor teardown",
    linkDescription: "Try the workflow",
    cta: "Sign Up",
    siteLabel: "your-brand.com/demo",
    activeDays: 4,
    isVideo: true,
    gradient: "linear-gradient(135deg, #111827 0%, #374151 50%, #9ca3af 100%)",
    funnel: "middle",
    format: "Video",
    lifespanDays: 11,
    angle: "Social proof",
  },
  {
    id: "own-tiktok-3",
    platform: "tiktok",
    pageName: DEMO_OWN_BRAND.name,
    body: "3 signals your competitor is scaling spend — and how to catch it before your board asks.",
    headline: "Spot spend spikes early",
    linkDescription: "Start free trial",
    cta: "Sign Up",
    siteLabel: "your-brand.com/pricing",
    activeDays: 8,
    isVideo: true,
    gradient: "linear-gradient(135deg, #0c4a6e 0%, #0369a1 50%, #38bdf8 100%)",
    funnel: "bottom",
    format: "Video",
    lifespanDays: 16,
    angle: "Urgency / insight",
  },
];

const OWN_STRATEGY_CELLS = [
  { platform: "Google", funnel: "TOF", ads: 22, spend: "€2.4k", activity: "High" },
  { platform: "Meta", funnel: "TOF", ads: 28, spend: "€3.1k", activity: "High" },
  { platform: "LinkedIn", funnel: "TOF", ads: 8, spend: "€0.9k", activity: "Testing" },
  { platform: "Google", funnel: "MOF", ads: 14, spend: "€1.6k", activity: "High" },
  { platform: "Meta", funnel: "MOF", ads: 18, spend: "€2.0k", activity: "High" },
  { platform: "Meta", funnel: "BOF", ads: 12, spend: "€1.8k", activity: "High" },
  { platform: "Google", funnel: "BOF", ads: 10, spend: "€1.4k", activity: "Testing" },
] as const;

const OWN_PLATFORM_IDS: Record<(typeof OWN_STRATEGY_CELLS)[number]["platform"], StrategyPlatform> = {
  Google: "google",
  Meta: "meta",
  LinkedIn: "linkedin",
};

function ownFunnelCell(
  platformLabel: (typeof OWN_STRATEGY_CELLS)[number]["platform"],
  funnel: FunnelStage,
  adCount: number,
  spend: string,
  activity: (typeof OWN_STRATEGY_CELLS)[number]["activity"],
): FunnelCellNodePayload {
  const platform = OWN_PLATFORM_IDS[platformLabel];
  const mid = Number(spend.replace(/[€,k]/gi, "").trim()) * 1000;
  const cellConfidence = activity === "High" ? "high" : "medium";
  return {
    id: `${platform}:${funnel}` as FunnelCellId,
    platform,
    label: platformLabel,
    funnelStage: funnel,
    adCount,
    estSpendEur: mid,
    estSpendEurLow: Math.round(mid * 0.82),
    estSpendEurHigh: Math.round(mid * 1.18),
    sampleAdIds: [],
    cellConfidence,
    position: { x: 0, y: 0 },
  };
}

const OWN_FUNNEL_CELLS = OWN_STRATEGY_CELLS.map((cell) =>
  ownFunnelCell(cell.platform, cell.funnel as FunnelStage, cell.ads, cell.spend, cell.activity),
);

export const OWN_STRATEGY_CHANNEL_SIGNALS: StrategyChannelSignals = {
  version: 1,
  computedAt: "2026-07-14T10:00:00.000Z",
  organicNodes: [
    {
      id: "organic:linkedin",
      platform: "linkedin",
      label: "LinkedIn",
      postCount: 18,
      postsPerWeek: 1.2,
      avgEngagement: 840,
      lastPostAt: "2026-07-13T08:00:00.000Z",
      topThemes: ["Product updates", "GTM playbooks"],
      pairedPaidPlatform: "linkedin",
    },
    {
      id: "organic:youtube",
      platform: "youtube",
      label: "YouTube",
      postCount: 12,
      postsPerWeek: 0.8,
      avgEngagement: 4200,
      lastPostAt: "2026-07-10T14:00:00.000Z",
      topThemes: ["Product demos", "Competitive teardowns"],
      pairedPaidPlatform: "google",
    },
  ],
  emailNode: {
    id: "email",
    label: "Email",
    emailCount: 9,
    emailsPerWeek: 1.1,
    dominantType: "promotional",
    dominantAngle: "Trial nurture",
    offerSharePct: 22,
    lastEmailAt: "2026-07-12T11:00:00.000Z",
    espDetected: "Customer.io",
  },
  channelEdges: [
    {
      from: "organic:linkedin",
      to: "linkedin:TOF",
      kind: "organic_to_paid",
      confidence: 0.74,
      reasoning: "LinkedIn organic thought leadership feeds TOF lead-gen ads.",
      style: "solid",
    },
    {
      from: "organic:youtube",
      to: "google:TOF",
      kind: "organic_to_paid",
      confidence: 0.7,
      reasoning: "YouTube demos support Google search and display TOF.",
      style: "dashed",
    },
    {
      from: "meta:BOF",
      to: "email",
      kind: "paid_to_email",
      confidence: 0.76,
      reasoning: "Trial signup flows capture emails for onboarding sequences.",
      style: "solid",
    },
  ],
};

export const OWN_STRATEGY_JOURNEY_GOAL: StrategyJourneyGoal = {
  version: 1,
  computedAt: "2026-07-14T10:00:00.000Z",
  kind: "signup",
  label: "Start free trial",
  subtitle: "Primary conversion outcome",
  catalogBreadth: "focused",
  catalogLabel: "Single product signup",
  topDestinations: [
    {
      url: "https://your-brand.com/pricing",
      displayUrl: "your-brand.com/pricing",
      adCount: 34,
      sharePct: 58,
    },
    {
      url: "https://your-brand.com/demo",
      displayUrl: "your-brand.com/demo",
      adCount: 14,
      sharePct: 24,
    },
  ],
  goalEdges: [
    {
      from: "meta:BOF",
      to: "goal",
      kind: "bof_to_goal",
      pathIntent: "direct_sale",
      pathIntentLabel: "Direct signup",
      alignment: "direct",
      confidence: 0.82,
      reasoning: "Meta BOF ads push pricing and signup pages.",
      style: "solid",
    },
    {
      from: "google:BOF",
      to: "goal",
      kind: "bof_to_goal",
      pathIntent: "lead_capture",
      pathIntentLabel: "Demo request",
      alignment: "direct",
      confidence: 0.78,
      reasoning: "Google BOF search ads capture high-intent trial keywords.",
      style: "solid",
    },
    {
      from: "email",
      to: "goal",
      kind: "email_to_goal",
      pathIntent: "nurture",
      pathIntentLabel: "Trial nurture",
      alignment: "supporting",
      confidence: 0.72,
      reasoning: "Onboarding emails drive activated trials after signup.",
      style: "dashed",
    },
  ],
  pathIntentBreakdown: [
    { intent: "direct_sale", label: "Direct signup", pathCount: 2, sharePct: 60 },
    { intent: "lead_capture", label: "Demo request", pathCount: 1, sharePct: 25 },
    { intent: "nurture", label: "Trial nurture", pathCount: 1, sharePct: 15 },
  ],
  evidence: {
    narrative:
      "BOF paths converge on trial signup. 22 BOF ads; primary destinations your-brand.com/pricing and /demo. Email nurtures trial activation.",
    deals: [{ label: "14-day free trial", source: "ad", code: null, channel: "meta" }],
    categories: [{ label: "SaaS signup", url: null, adCount: 22, sharePct: 72 }],
    topCreatives: [
      {
        adId: "own-meta-1",
        platform: "meta",
        imageUrl: null,
        headline: "Try free for 14 days",
        angle: "Free trial",
        landingUrl: "your-brand.com/pricing",
      },
    ],
    landingPreviews: [
      {
        url: "https://your-brand.com/pricing",
        displayUrl: "your-brand.com/pricing",
        adCount: 34,
        sharePct: 58,
        categoryLabel: "Pricing",
        previewImageUrl: null,
        platforms: ["meta", "google"],
      },
    ],
    angleHighlights: ["Free trial", "Product-led", "Demo CTA"],
    emailOfferSummary: "2 of 9 emails mention extended trial or onboarding incentives",
  },
  journeySummary: "Organic → Paid ads → Email → Start free trial",
  macroFraming: "Product-led growth: content warms audiences, paid captures intent, email activates trials.",
  signals: ["Pricing-heavy BOF", "Demo page secondary path", "Lean channel mix"],
  confidence: 0.81,
};

export const OWN_STRATEGY_MAP: StrategyMapPayload = {
  title: `${DEMO_OWN_BRAND.name} Full Funnel Strategy Map`,
  competitor: {
    name: DEMO_OWN_BRAND.name,
    domain: DEMO_OWN_BRAND.domain,
    logoUrl: null,
  },
  totalAdSpend: {
    value: 9200,
    low: 6000,
    high: 14000,
    currency: "EUR",
    unit: "month",
    confidence: "medium",
    brandScaleScore: 2.1,
  },
  spendVsSimilar: "Medium",
  spendTrendline: [18, 20, 22, 24, 26, 28, 27, 29, 30, 31, 32, 30],
  audienceSignals: {
    interests: ["Growth marketers", "Performance teams", "SaaS founders"],
    ageRange: "25–44 primary",
    geo: "US + EU English markets",
    targetingType: ["Job title", "Interest clusters", "Retargeting"],
  },
  dominantFormat: { format: "Image", percentage: 42 },
  toneOfVoice: {
    primary: "Product-led / helpful",
    attributes: ["Clear", "Educational", "Direct"],
  },
  topAngles: [
    { angle: "Free trial / signup", rank: 1 },
    { angle: "Competitive intelligence hook", rank: 2 },
    { angle: "Feature demo", rank: 3 },
  ],
  sidebarExtras: {
    formatMix: [
      { label: "Image", sharePct: 42 },
      { label: "Search", sharePct: 28 },
      { label: "Video", sharePct: 22 },
      { label: "Display", sharePct: 8 },
    ],
    angleCategories: [
      { label: "Trial", count: 38, sharePct: 44, category: "lead_capture" },
      { label: "Education", count: 24, sharePct: 28, category: "brand_awareness" },
      { label: "Demo", count: 18, sharePct: 21, category: "product_push" },
    ],
    voiceConfidence: 0.79,
  },
  platformNodes: [],
  funnelCells: OWN_FUNNEL_CELLS,
  funnelEdges: [],
  activeAdCount: 118,
  platformCount: 3,
  derivationQuality: "high",
};

export const OWN_TIMELINE_DATE_RANGE = {
  earliest: "2026-04-01T00:00:00.000Z",
  latest: "2026-07-15T12:00:00.000Z",
} as const;

export const OWN_TIMELINE_ADS: TimelineAd[] = [
  {
    id: "own-meta-1",
    platform: "meta",
    ad_creative_url: null,
    ad_text: OWN_ADS[0]!.body,
    ai_extracted_angle: null,
    first_seen_at: "2026-05-12T12:00:00.000Z",
    last_seen_at: "2026-07-14T12:00:00.000Z",
    format: "Image",
    is_winner: false,
    is_killed: false,
  },
  {
    id: "own-meta-2",
    platform: "meta",
    ad_creative_url: null,
    ad_text: OWN_ADS[1]!.body,
    ai_extracted_angle: null,
    first_seen_at: "2026-06-01T12:00:00.000Z",
    last_seen_at: "2026-07-14T12:00:00.000Z",
    format: "Video",
    is_winner: false,
    is_killed: false,
  },
  {
    id: "own-google-1",
    platform: "google",
    ad_creative_url: null,
    ad_text: OWN_ADS[3]!.body,
    ai_extracted_angle: null,
    first_seen_at: "2026-04-20T12:00:00.000Z",
    last_seen_at: "2026-07-14T12:00:00.000Z",
    format: "Search",
    is_winner: true,
    is_killed: false,
  },
  {
    id: "own-linkedin-1",
    platform: "linkedin",
    ad_creative_url: null,
    ad_text: OWN_ADS[6]!.body,
    ai_extracted_angle: null,
    first_seen_at: "2026-05-28T12:00:00.000Z",
    last_seen_at: "2026-06-30T12:00:00.000Z",
    format: "Image",
    is_winner: false,
    is_killed: true,
  },
  {
    id: "own-tiktok-1",
    platform: "tiktok",
    ad_creative_url: null,
    ad_text: OWN_ADS[8]!.body,
    ai_extracted_angle: null,
    first_seen_at: "2026-06-18T12:00:00.000Z",
    last_seen_at: "2026-07-14T12:00:00.000Z",
    format: "Video",
    is_winner: false,
    is_killed: false,
  },
];

export const OWN_CREATIVE_TESTS: DemoCreativeTest[] = [
  {
    id: "own-ct-1",
    launch_date: "2026-06-24",
    platform: "meta",
    ad_ids: ["own-ct-1-a", "own-ct-1-b"],
    winner_ad_id: null,
    test_status: "running",
    median_lifespan_days: 14,
    max_lifespan_days: 17,
    winner_lifespan_days: null,
    ad_count: 2,
    ads: [
      {
        id: "own-ct-1-a",
        platform: "meta",
        ad_creative_url: null,
        ad_text: "Try free for 14 days — variant A",
        ai_extracted_angle: null,
        first_seen_at: "2026-06-24T12:00:00.000Z",
        last_seen_at: "2026-07-14T12:00:00.000Z",
        format: "Image",
      },
      {
        id: "own-ct-1-b",
        platform: "meta",
        ad_creative_url: null,
        ad_text: "Try free for 14 days — variant B",
        ai_extracted_angle: null,
        first_seen_at: "2026-06-24T12:00:00.000Z",
        last_seen_at: "2026-07-12T12:00:00.000Z",
        format: "Image",
      },
    ],
  },
  {
    id: "own-ct-2",
    launch_date: "2026-06-10",
    platform: "google",
    ad_ids: ["own-ct-2-a", "own-ct-2-b"],
    winner_ad_id: "own-ct-2-a",
    test_status: "winner_identified",
    median_lifespan_days: 22,
    max_lifespan_days: 28,
    winner_lifespan_days: 28,
    ad_count: 2,
    ads: [
      {
        id: "own-ct-2-a",
        platform: "google",
        ad_creative_url: null,
        ad_text: "Ad intelligence platform — winner headline",
        ai_extracted_angle: null,
        first_seen_at: "2026-06-10T12:00:00.000Z",
        last_seen_at: "2026-07-08T12:00:00.000Z",
        format: "Search",
      },
      {
        id: "own-ct-2-b",
        platform: "google",
        ad_creative_url: null,
        ad_text: "Track competitor ads — challenger headline",
        ai_extracted_angle: null,
        first_seen_at: "2026-06-10T12:00:00.000Z",
        last_seen_at: "2026-06-28T12:00:00.000Z",
        format: "Search",
      },
    ],
  },
];

export const OWN_DEFAULT_VISIBLE_PLATFORMS: DemoPlatform[] = [
  "meta",
  "google",
  "pinterest",
  "tiktok",
  "linkedin",
];
